### ISSUE TITLE
Implement a standard right-click menu

### ISSUE THREAD

**Issue by InconsolableCellist** [Jelmerro/Vieb#102]
Steps to reproduce:
1. Type `:set mouse` to enable mouse mode
2. Go to a site, like duckduckgo.com
3a. Right click on a link
3b. Right click on selected text 
3c. Right click on empty space

Observed behavior: 
3a,b,c: no right click menu

Expected behavior, at a minimum:
3a. A right click menu appears allowing you to open the link in the current tab/window or a new tab/window, or save the link, or copy the link to your system clipboard (in X: CLIPBOARD, not PRIMARY)
3b. Menu appears to let you copy selected text or search for selected text
3c. Menu appears to let you navigate back/forward, reload the page, or save page as

**Comment by Jelmerro** [comment]
Could definitely be added, should also be available in insert mode regardless of the mouse setting.

**Comment by Jelmerro** [comment]
I briefly checked available modules, and it seems like https://github.com/sindresorhus/electron-context-menu could have been great for this feature to be implemented. However, that module is useless when the remote module is disabled, due to [this issue](https://github.com/sindresorhus/electron-is-dev/issues/22) in one of the dependencies. This looks like something that can only be solved by replacing the entire is-dev module with `false`, or by removing the requirement of this package in the context-menu module. Though even in Electron's main thread the context-menu module doesn't seem to be able to create a working menu, at least not using the example code from the readme.

For Vieb, this leaves a total of four options to implement a context-menu the way I see it as of now:

- Use a different package (maybe https://github.com/reZach/secure-electron-context-menu could work)
- Build it custom in main using the `MenuItem` and `Menu` modules of Electron and communicate with those from the renderer
- Trying to extract the some parts context-menu package to make it work for modern Electron versions (licenses are compatible, but realistically this approach probably wouldn't differ much from the one above)
- Create it from scratch as a regular DOM element which will be absolutely positioned when something is right-clicked and will call existing actions on click (this is possibly the only solution that will work in webviews)

My preference is moving more and more towards just building it from scratch for Vieb, as the existing packages all seem to need communication with the main thread, which won't be needed for most actions in Vieb's case. It's also the only solution that is guaranteed to work, as the others are still up for discussion if they can even be made to work inside webviews. Another advantage is that unlike all other options, this type of menu can be themed and customized like other parts of Vieb's GUI.

**Comment by Jelmerro** [comment]
I decided to implement this from scratch as explained above. You can now check this feature on master, or wait for the next stable release to use it. Only thing I couldn't figure out was how to copy images on right-click, but you can save or open them, so it's good enough for now. Feel free to make new issues for missing or new right-click actions, or even implement them via PR.
