### ISSUE TITLE
Implement a quick site history in explore mode, similar to command history

### ISSUE THREAD

**Issue by InconsolableCellist** [Jelmerro/Vieb#107]
It'd be nice to hit `:` or `e` and immediatley see a pop-up list of recently used commands/sites, respectively, and be able to go through them with the up/down arrows or tab.

Oftentimes I'll have entered a command or visited a site in Pentadactyl and will want to do it again, so I'll hit `:` and go through recent commands with the up arrow.

**Comment by InconsolableCellist** [comment]
For example, I must've typed `:map <C-h> <:history>` and realized I wanted `:nnoremap` or something else, so I hit `:` and tried to go back to see what I entered, but couldn't.

**Comment by Jelmerro** [comment]
The command history is available already, try `<C-p>` and `<C-n>`, same as in Vim. See `:h action.commandHistoryPrevious` for details.

There is no such thing yet for explore mode, because I don't think it would be too useful. If you wanted to open the same website again, just to press `T` (shift-t) to open a new tab with the current tab's url. See `:h action.openNewTabWithCurrentUrl` for details.

Let me know if you are looking for more/different functionality besides that. If this is all you need, feel free to close the issue.

**Comment by InconsolableCellist** [comment]
Thanks. I'll have to bind the arrow keys like that so it works as I expect. I can close this one unless you want to consider it for explore mode. I didn't mean I wanted the same website as the one open, just one I had previously browsed to, but didn't want to open the entire history. Like, "damn I closed that tab five tabs ago, but don't remember what it was exactly."

**Comment by Jelmerro** [comment]
Alright, good to hear that you solved it for command mode. Regarding the explore mode history, I would personally rely on the explore mode suggestions, or just open the history page. But if you feel like it would help to have the same kind of quick history for websites as we currently have for commands, let me know.

**Comment by InconsolableCellist** [comment]
I think it'd help, but since it works in command mode and there's already history for explore, I'd put this as lower priority, personally. Thanks

**Comment by Jelmerro** [comment]
Implemented on `master`, let me know if this is what you had in mind @InconsolableCellist

**Comment by Jelmerro** [comment]
Latest release includes this, feel free to open a new issue for followup changes or questions.
