### ISSUE TITLE
Opening links in the current tab through javascript

### ISSUE THREAD

**Issue by BachoSeven** [Jelmerro/Vieb#118]
Hi, I use a custom startpage which is a local html file with a search bar, which has some javascript in it. I use the `window.open` method to open different sites from this search bar, and I use the `_self` target as the window name.

Now, while this works in chromium(the site opens in the current tab, replacing my startpage), in `Vieb` they open in a new tab.

I have tried to find a solution, and found that one can enable using the native implementation of `window.open` in Electron, documented [here](https://www.electronjs.org/docs/api/window-open#using-chromes-windowopen-implementation). This solves my issue (by setting `webview.setAttribute("webpreferences", "nativeWindowOpen=yes")`, for example in `apps/js/tabs.js` from the DevTools).

Now since I don't think I can set such option from my javascript, what do you think could be a solution for this? Could you add an option for enabling `nativeWindowOpen`? Any suggestion is welcome, and thanks in advance.

**Comment by Jelmerro** [comment]
Just to make this clear: in Vieb it's up to the user to choose if links open in a new tab, not up the websites. You can open follow mode in the newtab mode, or the regular mode. These will always open the url in the location that the user decided to choose by opening the right variation of follow mode.

Regarding the issue that you are having, it's probably caused by the fact that new windows are always opened in a new tab, unless Electron detects it as a foreground tab. You could check/log the code [here](https://github.com/Jelmerro/Vieb/blob/3.2.0/app/js/tabs.js#L690) to confirm this, and possibly fix this. Using the native window open code is not the right solution and will probably affect other Vieb related actions. The documentation for the referenced event can be found [here](https://www.electronjs.org/docs/api/webview-tag#event-new-window).

If possible, please include some example code of the website that show this behavior, so that I can also take a look myself what could be the issue.

Unrelated to Vieb, opening links in the current tab with JavaScript sounds just like a regular navigation such as `window.location = 'https://vieb.dev'` for example. Is there any reason to use `window.open` for this?

**Comment by BachoSeven** [comment]
The code was [this](https://github.com/bachoseven/startpage/tree/master/js/search.js#L32), but using `window.location` fixes my issue. I was originally using `window.open` for opening links in a new tab and I needed the method to focus the tab.

Thank you very much for the suggestions!

**Comment by BachoSeven** [comment]
> Just to make this clear: in Vieb it's up to the user to choose if links open in a new tab, not up the websites. You can open follow mode in the newtab mode, or the regular mode. These will always open the url in the location that the user decided to choose by opening the right variation of follow mode.

Regarding that part of your comment: using `f` follow-mode on the "`Cursorcer`" link in [this](https://ahmadawais.com/hide-cursor-mac-os/) website (or any other link on that page) opens it in another tab(and left-clicking it has the same behaviour). Should I open another issue for this?

**Comment by Jelmerro** [comment]
Good find, I'll work on this soon, you can open a new issue if you want to, but expect this to be solved soon.

**Comment by BachoSeven** [comment]
I see you have made some commits related to it, just wanted to report that I still experience the behaviour mentioned above, running from master.

**Comment by Jelmerro** [comment]
That's interesting, because I used your site as the one to test the new code with. Are you sure that you are running the latest code on master? What does `git pull` report when you execute it? I just tested it again, and here it works as expected.

**Comment by BachoSeven** [comment]
Okay I tried again, and `f` works, however left-clicking the link does not. Perhaps left-click is not supposed to behave like `f` though, since vieb is obviously keyboard-centered.

**Comment by Jelmerro** [comment]
Yes, the mouse does not behave the same way as follow mode, as that adds a lot of complications to prevent tabs from opening in these cases. Historically, using the mouse in Vieb is actually an afterthought, but I do welcome PRs to make it more usable with a mouse.
