### ISSUE TITLE
Toggle tab bar

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#119]
For maximum screen I set urlbar and tabbar to onupdate. 
Is there a way to set a keybinding to toggel it on and off?

**Comment by Jelmerro** [comment]
When the visibility settings for the urlbar and tabbar are set to "onupdate", they will reappear when you change something in that specific bar, such as opening or closing tabs for the tabbar, and switching to explore/command mode for the urlbar. You can even set the delay at which these will hide again with `guihidetimeout`.

If you want to toggle the actual setting, you'll have to make two keybindings, because it's not a setting that can be toggled (as there are more possible values than just 2). You can for example do `:nmap <F2> <:set guitabbar=onupdate guinavbar=onupdate>` and `:nmap <F3> <:set guitabbar=always guinavbar=always>`. Of course you can use other keys beside F2 and F3, and you can also change the settings one at a time if you just want to toggle one of them.

**Comment by se7en-x230** [comment]
exellent works like a charm 
one more question.
What's the code to map the windows key to an action?

**Comment by BachoSeven** [comment]
@se7en-x230 I believe that the Windows/Super key is Meta in this context, so for instance
``` vim
map <M-Q> <:quit>
```
(found in the [chromium](https://github.com/Jelmerro/Vieb/blob/master/app/examples/chromium) configuration example

**Comment by se7en-x230** [comment]
@BachoSeven thanks as always :)

**Comment by kekscode** [comment]
Just something to point out, because i like @se7en-x230 idea of having a
mapping for toggling the ui visuals. I just happen to use `<` and `>` and Vieb
is a little bit special here (but well documented).

I tried the following setting, thinking i know what i'm doing:

```
nmap < <:set guitabbar=onupdate guinavbar=onupdate>
nmap > <:set guitabbar=always guinavbar=always>
```

But this does not work. Especially not if your Vieb is starting with a
visible tabbar/navbar. This is documented behaviour in the online help:

The `<` sign has to be used as `<lt>` while the greater then is just `>` (`<gt>` does NOT exist).

This works:

nmap <lt> <:set guitabbar=onupdate guinavbar=onupdate>
nmap > <:set guitabbar=always guinavbar=always>

**Comment by Jelmerro** [comment]
Glad to hear this is resolved. I think I'll make a new type of ticket in the future to also ask questions, that seems to be missing currently. Though you can also do that on [r/vieb](https://www.reddit.com/r/vieb/) of course.
