### ISSUE TITLE
Cannot find module 'is-svg'

### ISSUE THREAD

**Issue by BachoSeven** [Jelmerro/Vieb#136]
**Describe the bug**
![image](https://user-images.githubusercontent.com/55460785/112729436-5dcd4a00-8f2c-11eb-9716-d44f55632110.png)

**To Reproduce**
Visit 
https://arstechnica.com/gadgets/2021/03/buffer-overruns-license-violations-and-bad-code-freebsd-13s-close-call/

**Specs**
 - OS: Arch Linux
 - Version: 4.2.0(`vieb` from the AUR, of which I'm the maintainer, so if this is a packaging issue I'll be glad to fix it).

Edit: this happens on many sites, not just the linked one

**Comment by Jelmerro** [comment]
Do you have the same problem when, for example, running the AppImage? Because I can't reproduce this (and I'm not using arch, so I can't test the arch package myself). The `is-svg` package is defined as a dependency in the `package.json`, so it should be installed when you run `npm install`. Though I'm not sure where this step should happen for the AUR packaging process.

**Comment by Jelmerro** [comment]
Okay, so this is also a problem for the RPM package, I am not sure what is causing this as of yet.

**Comment by BachoSeven** [comment]
> Do you have the same problem when, for example, running the AppImage? Because I can't reproduce this (and I'm not using arch, so I can't test the arch package myself). The `is-svg` package is defined as a dependency in the `package.json`, so it should be installed when you run `npm install`. Though I'm not sure where this step should happen for the AUR packaging process.

I just extract the release `.pacman` archive in `/opt`, so it _should_ work as well as `.deb`s

**Comment by Jelmerro** [comment]
It's not a packaging issue for your AUR package. This is due to the changes I made to delay imports. This was recommended [here](https://www.electronjs.org/docs/tutorial/performance), but this causes the modules to be excluded from the Vieb package when being built with electron-builder. Whether this is an Electron or an electron-builder issue is something I have to look into in detail, but for now I'll undo the performances improvements so that it works. Kind of weird that Electron would recommended this, even though it breaks packages....

**Comment by BachoSeven** [comment]
I see. I was, in fact, seeing some performance improvements

**Comment by Jelmerro** [comment]
Most likely due to the modules not loading at all, instead of being loaded at the app startup :wink:

**Comment by Jelmerro** [comment]
This is definitely due to electron builder, I tried reverting the performance changes and the problem still occurs. AND I can see a lot of similar [issues](https://github.com/electron-userland/electron-builder/issues):
- https://github.com/electron-userland/electron-builder/issues/5707
- https://github.com/electron-userland/electron-builder/issues/5713

I'll check if downgrading Electron solves it, as it's a recent problem and electron-builder hasn't been upgraded for a while.

**Comment by Jelmerro** [comment]
That also doesn't work, I am running out of things to check what it could be, but this is definitely a bigger issue that many people seem to have, even with versions that used to work for past releases.

**Comment by Jelmerro** [comment]
I have made a new release that should fix this bug, let me know the results. I apologize for the bad 4.2.0 release.

**Comment by BachoSeven** [comment]
Seems fixed on my end. Closing this

**Comment by Jelmerro** [comment]
That's a relief, spend a couple of hours debugging where this went wrong actually. Kind of weird how it only affected the released builds, and AppImage didn't seem affected here. Glad it's fixed now.
