### ISSUE TITLE
Some favorites doesn't have icons nor names

### ISSUE THREAD

**Issue by ByJumperX4** [Jelmerro/Vieb#144]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Some websites won't have icons nor names when added to favorites

![image](https://user-images.githubusercontent.com/48773926/113423434-bc804100-93ce-11eb-85e3-b56f80c815b2.png)

**To Reproduce**
Add some favorites, and find some websites that won't work

**Expected behavior**
Every favorite should have an icon and a name

**Specs**
 - OS: Funtoo w/ dwm
 - Version: latest master compiled from source

**Comment by Jelmerro** [comment]
This is likely because you haven't visited these pages yet. Fetching the correct favicon and title require a connection to the page to be made, which Vieb will NOT do when you add favoritepages. One of Vieb's core aspects is privacy, which also comes with a handful of drawbacks. The favicons are cached, so you only need to visit them once, but it won't automatically connect to sites just because you updated some local setting. The same is true for other settings and most other features. The only notable exception is when you ask Vieb to automatically update the adblocker lists, that can only be done by making a request, for which Vieb will always show a notification when this happens.

Let me know if I was correct to assume you haven't visited these pages or if you think there is a different problem happening.

**Comment by ByJumperX4** [comment]
I did visited those pages, I visit them all very often

**Comment by Jelmerro** [comment]
Can you check if the url matches with the one recorded in your history?

**Comment by ByJumperX4** [comment]
I think it's that, it redirects to something else, like git.gnous.eu that goes to git.gnous.eu/explore/repos

**Comment by Jelmerro** [comment]
Right, currently there isn't any logic to keep these redirects linked to a favicon, as that url doesn't actually have one. Same for the title. I see two options to handle these type of redirects:

- Assume that redirecting sites have the same title and favicon (this isn't very reliable or correct)
- Only store and match this data for the same urls (current behavior)

If you have any other suggestions, let me know, but these seem to me like the only two options.

**Comment by ByJumperX4** [comment]
Maybe adding an option like `:set favoritepagesreditects true` ?

**Comment by Jelmerro** [comment]
This is not only for favoritepages though, but also for topsites and other places. Besides, a setting like that would only take effect the next time you would visit that page, because it would require storing this as the redirect happens. Speaking of which, I'm not sure how redirects are actually communicated with Electron and if we would need to check only same domain redirects or allow any redirect to have this behavior.

**Comment by Jelmerro** [comment]
Turns out that there are APIs in electron to catch redirects, I'll update the favicon and page title mappings with them shortly. That should resolve most of this issue, but you'll always need to visit the page at least once to get the favicon as Vieb won't request it in the background.

**Comment by Jelmerro** [comment]
Let me know if my [latest commit](https://github.com/Jelmerro/Vieb/commit/37088f1d30d9216a04ac5cda0ef474d7552c96e6) fixes this issue for you as well.

**Comment by Jelmerro** [comment]
Implemented in the latest release 5.1.0 release.
