### ISSUE TITLE
Add more `<C-w>` window split mappings

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#146]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
A command to switch to the last split like vim's `CTRL-W_w`.
This would be a nice alternative to having to switch splits using `CTRL-W H,J,K,L`.

**Alternatives considered**
Using `h,j,k,l` is fine, but `w` is more convenient for switching back and forth as I don't need to know which direction the last split was  in to switch to it.

**Comment by Jelmerro** [comment]
Seems like a nice addition. I might work on this in the near future if I find the time, but if anyone else wants to work on this, feel free to make a PR.

**Comment by ottopiramuthu** [comment]
For a browser with such an impressive adherence to vim's commands I was surprised this wasn't there. Glad to help filling the gaps :)

**Comment by Jelmerro** [comment]
I made a commit that adds a bunch of the more simple actions that were missing and a new ":only" command, including default mappings under `<C-w>` for all of them. I think pretty much all relevant actions listed in Vim's `:h windows.txt` are now actually present in Vieb. Notable exceptions that could still be added:

- `<C-w>p` for going to the previous window splits based on focus instead of merely being adjacent, which will require a history of focused splits. Not sure about the details of this Vim action actually, I most use the ones that were already present before my latest commit. If anyone could explain this action in more detail than the Vim help, that would be great.
- `<C-w>R` reverse rotate of splits. Currently only forward rotation is implemented, I wasn't aware that holding shift while pressing `r` would reverse the rotation direction. I'm not sure about the naming scheme as the original rotate action added in Vieb doesn't contain a direction in it's name, so that might get confusing if we would add this.
- `<C-w>x` changing the order of splits by exchanging positions of the current split with the next one (or previous if current one is the last one). Probably the most hassle-free to add of these three listed ones.

Let me know if there are any other actions or commands that are missing with regards to window splitting that seem relevant to add in Vieb.

**Comment by Jelmerro** [comment]
Just today I implemented the last three missing actions including default mappings. With that done, I believe this issue can be closed. Feel free to check it out by running from source, or wait for the next release to try them. If anyone has any other ideas about window splitting or even missing mappings, please make a new issue.
