### ISSUE TITLE
Can't scroll using `hjkl` in some websites

### ISSUE THREAD

**Issue by python-clojure** [Jelmerro/Vieb#150]
In the following website, neither the `hjkl` keys nor the arrow keys work for scrolling. See the website link below
[Notion Enhancer](https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041)

Permission command run : `set permissionmediadevices=allowfull`

**Comment by Jelmerro** [comment]
This is because strictly speaking the page isn't scrollable at all. There is a part of the page that can be scrolled, it's just that most of the page is covered by it. You can scroll at a specific position using pointer mode. The differences between the two types of scrolling Vieb are explained at `:h scrolling`. Though it might not be the answer you hoped for, there is nothing to be fixed here for Vieb. A tip I will give, is that you can execute the pointer scrolling outside of pointer mode, if you make a mapping for it, but the location of the scroll action will still be at the pointer position. If you have any questions about this, please ask them.
