### ISSUE TITLE
Syntax to toggle/cycle settings through different values

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#152]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Normally only binary settings can be toggled like `:set ignorecase!`.
I would like to be able to toggle/cycle a setting through multiple values.
For example, having something like `map <F4> <:set guitabbar!always,never,onupdate>` in my viebrc would cycle between "always", "never", and "onupdate" options for the tab bar in the given order. I don't have any specific requests regarding the syntax; I just want a way to cycle all settings between multiple options. Adding the `if` and `else` from vimscript could also be a nice alternative way to do this.

**Alternatives considered**
Using different mappings to set different values: this becomes a mess to manage(takes too many keys away that could be use for other mappings)/remember when there are too many values to cycle through, and having one mapping to cycle through values is much more convenient.

**Comment by Jelmerro** [comment]
I don't mind adding this, I was thinking along the lines of adding a suffix character similar to `&` or `!` to cycle through all available options. Of course we can only add this for options that have a fixed set of possibilities, otherwise I think this might get a bit too complex to manage or explain to users, compared to just adding a separate mapping. For more advanced scenarios I think it would be better to implement `if` and `else` structures and other more code-like features into command mode and the viebrc, without changing the set syntax too much. I might prefer that in the long-term actually, I'll think about this for for a while.

**Comment by Jelmerro** [comment]
Implemented in [V5](https://github.com/Jelmerro/Vieb/releases/tag/5.0.0).
