### ISSUE TITLE
Add vim-like marks for jumping to different parts of websites

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#166]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add commands to make marks for positions in a site similar to those in Vim: `m{a-zA-Z}` to make a mark, `'{a-zA-Z}` to jump to the mark.

**Alternatives considered**
Using HTML anchors: not every page has convenient anchors.

**Comment by Jelmerro** [comment]
I like this idea, it seems much more closer to Vim to use marks for positions on the page, instead of using them for (previously proposed) bookmarks/"quickmarks. Though about these marks, would they be stored per site, per session or should they be persistent? And would they just remember the scroll position, or something else? I personally don't use marks very often in Vim, so I'm probably not the right person at the moment to work on implementing such a feature in Vieb.

**Comment by ottopiramuthu** [comment]
They would probably be per session since by default Vim doesn't save marks after it is closed. 

Marks in Vim remember the row and column of the cursor. While `'a` moves the cursor to the start of the line of mark `a`, `` `a `` will move the cursor to the exact position of the mark. Maybe in Vieb mark jumping could have the behavior of `'a` in normal mode (scroll to position) and the behavior of `` `a `` in pointer mode (move pointer to the exact position).

Another detail is that marks with capital letters (`m{A-Z}`) are accessible from any file. So in Vieb for example, if the mark `A` is set on one tab, typing `mA` could bring the user to the tab and position with `A` no matter which tab the user is on.

**Comment by debboutr** [comment]
like this idea. I just found `Vieb`, am normally a `Vimium` user, I use the capital [A-Z] global marks to bookmark pages, works really well.

**Comment by Jelmerro** [comment]
Now released as 9.0.0!
