### ISSUE TITLE
Cannot run under MacOS (ARM silicon Mac)

### ISSUE THREAD

**Issue by imTHAI** [Jelmerro/Vieb#169]
Hello,
I downloaded the specific version ( Vieb-4.4.0-mac-arm64.zip) but when I try to run it, I get:
![Capture d’écran 2021-04-26 à 08 27 37](https://user-images.githubusercontent.com/36070606/116038220-76369e80-a669-11eb-9ec8-604cd56594b1.png)

Rmq: But the intel version works.

**Comment by Jelmerro** [comment]
Did you check [these](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#mac) instructions from the frequently asked questions?

**Comment by imTHAI** [comment]
Hello, 
No, I didn't know about, but those instructions are Mac specifics. And I didn't need to do anything special to launch the intel version. Plus, those instructions explain how to run an application from a not identified developper. Basically, I just have to right-click and choose open, but here it stil gives the same error message.

**Comment by Jelmerro** [comment]
Alright, can you maybe translate the error message from French to English? Because I clearly misunderstood the issue then. It's really odd that the Intel version works on a Silicon chip, but I have never actually had an M1 laptop to test this on, so who knows.

**Comment by Jelmerro** [comment]
It seems that the signing requirements for M1 Silicon apps are even more strict compared to regular apps. Did you try to sign the `.app` locally using the linked instructions before running? Because merely allow unidentified developers does not seem sufficient for native M1 apps:
"
New in macOS 11 on Macs with Apple silicon, and starting in macOS Big Sur 11 beta 6, the operating system enforces that any executable must be signed before it’s allowed to run. There isn’t a specific identity requirement for this signature: a simple ad-hoc signature is sufficient. This new behavior doesn’t change the long-established policy that our users and developers can run arbitrary code on their Macs, and is designed to simplify the execution policies on Macs with Apple silicon and enable the system to better detect code modifications. This new policy doesn’t apply to translated x86 binaries running under Rosetta 2, nor does it apply to macOS 11 running on Intel-based platforms.
"
See [here](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes).

Apple has decided that signing the app yourself is the ONLY exception for allowing you to run unsigned apps, as explained above. I ask of you to try the instructions listed instead of merely right-clicking on the app and saying it doesn't work, the FAQ exists for a reason. This is not something that can be fixed, worked on, or otherwise improved, for long as Apple continues to restrict signing to macos only. The only two options are properly following the FAQ instructions, or building Vieb yourself with the instructions from the readme.

**Comment by imTHAI** [comment]
Hello @Jelmerro 
Just so you know (or have confirmation):
I didn't know what you said about "that the signing requirements for Silicon apps are even more strict compared to regular apps.", so after I've read you, I tried. I did:
`sudo codesign --force --deep --sign - /Applications/Vieb.app`
And it did the trick indeed ! So voilà. Have a nice day
