### ISSUE TITLE
vieb can't read login's information of another tab

### ISSUE THREAD

**Issue by BeyondMagic** [Jelmerro/Vieb#172]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When trying to login in a site that uses Google as one of the ways to login, it opens a new tab (Google specifically here), after logging the tab closes and the site is not able to load the Google's information (or get it?).

![image](https://user-images.githubusercontent.com/51831435/116450400-a466da80-a831-11eb-8ff6-666d343ad064.png)

**Note that this is not a problem with logging to Google, but to the website!**

**To Reproduce**
+ Opens https://www.khanacademy.org/login.
+ Click on "Continue with Google"
+ Login in your account on Gmail
+ See error on the the site's page

**Expected behavior**
Continues the login

**Specs**
 - OS: Artix Linux
 - Version: 4.4.0

**Comment by Jelmerro** [comment]
I don't have any of the accounts listed here that would allow a quick signin, but it's because the site expects a popup, but instead it's opened as a new tab. The data is shared fine between multiple tabs, but the message clearly mentions the problem being the popup. There is no way to dynamically allow popups in electron, you either enable them globally or block them all, which is also the default. As such, popups are opened in a new tab. Some websites don't properly deal with this, and I would recommend to get in touch with the site to let them know that their site relies on popups for the quick signin, which a lot of browser are actually blocking by default nowadays, it's even recommended to move away from `window.open` on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#usability_issues). For more info about the popups not being supported, see [this issue](https://github.com/Jelmerro/Vieb/issues/67). See my last comment in that thread for the only possible workaround, though I won't recommend it, as it's a fairly annoying to allow all popups globally (which is, as mentioned, the only option to allow them at all).

**Comment by Jelmerro** [comment]
I have added an entry in the FAQ about this, as an issue about popups has been opened before.
