### ISSUE TITLE
Cheatsheet for default Vieb bindings

### ISSUE THREAD

**Issue by python-clojure** [Jelmerro/Vieb#203]
I have checked the help page of Vieb but I didn't see any cheatsheet like the one below. This is taken from `qutebrowser`. It is also a Vim-based browser. It is always crashing a lot. I can't even stay on the website for more than a minute. Is there any keybinding cheatsheet like the one below? This also has nice keybindings like copying a hinted URL (extended hinting mode) etc. Are there features similar to this in Vieb? I really want to switch to this one from `qutebrowser`. As I said, it always crashes like hell. I have been using yours parallelly for several months and I have never witnessed your browser crashing even once. That is really nice. Are there features, keybindings and cheatsheet similar to the one below?

![cheatsheet-big](https://user-images.githubusercontent.com/49131888/120300745-d7493600-c2e9-11eb-9285-f14cf0172362.png)

**Comment by ottopiramuthu** [comment]
Qutebrowser has a `.svg` file for the cheatsheet [here](https://github.com/qutebrowser/qutebrowser/blob/master/misc/cheatsheet.svg). We can probably use that as a base.

**Comment by Jelmerro** [comment]
There is no such chart for Vieb yet that I know about, but feel free to make one. There is actually a fair amount of keys listed that are similar, but also of course things that are very different. A thing to note is that Vieb is fundamentally different when handling mappings, in that all keyboard shortcuts are implemented by binding actions or commands to specific keys, similar to Vim. This means that even if such a sheet would be created, it would only be relevant for the default mappings. To prove my point, there are example configs to make Vieb work like, Chromium, Firefox, Vimium etc. that can be found [here](https://github.com/Jelmerro/Vieb/tree/master/app/examples) or using `:h examples` while in Vieb. There is no example for qutebrowser yet, but that would be great to have as well. You can find the main issue regarding migration guides and comparisons [here](https://github.com/Jelmerro/Vieb/issues/83).

To anyone interested in making a chart like this: feel free to do so, and please let us know via [github discussions](https://github.com/Jelmerro/Vieb/discussions) or the official [subreddit](https://reddit.com/r/vieb).

**Comment by Jelmerro** [comment]
I forgot to mention, you can list all default mappings with `:map!`, you can find more info about mappings using `:h mappings`.

Also, all of Vieb's actions that have any reason to be countable ARE countable, but only when in normal, menu, pointer or visual mode. In other modes, the count is always 1.

**Comment by ottopiramuthu** [comment]
This is an attempt to edit Qutebrowser's cheatsheet to fit Vieb's mappings:

![cheatsheet](https://user-images.githubusercontent.com/49997309/121257283-84d4c000-c87b-11eb-88bd-47c25e6ef073.png)

Clearly this is not complete and many more mappings can be added, I'm just wondering what sections (below the keyboard) you would suggest using for listing extra mappings.

I was thinking something like:
- scrolling
- URL editing
- tab management
- insert-mode mappings
- command-mode mappings
- explore-mode mappings
- follow-mode mappings

But I really don't know how to organize these mappings clearly.. any advice on this is welcome :)

**Comment by Jelmerro** [comment]
Great that we have a first version ready, there are a couple of things missing as you noticed as well:

- `D` to download the current link (not the webpage, just the link) (technically countable)
- `-` and `+` are countable and besides that, `_` and `=` are also mapped to the same actions for convenience
- `N` goes to the previous match and both `n` and `N` are countable (though those are already blue)
- `x` is technically countable, as are `P`, `t` and all the scrolling actions
- `c` also goes to pointer mode
- `r` isn't countable, neither is `R` (but that one already is in black)
- `th` isn't by default mapped to anything, might be a typo or leftover from the original?
- `Enter` can be used to click on the current search result (the one in orange, not in yellow)
- `w` and `b` are also shortcuts to switch between tabs, also countable
- Maybe besides the website we could also mention the subreddit and this github repo

Since you mention these are the default mappings, maybe include a brief explanation that these are completely customizable and redirect them to the map commands (and the help page for those). I would also like `F1` to be mentioned on here somewhere. I would also suggest to scroll through the help a bit to find things we both overlooked, and to double-check all the countable actions (those `countable` badges on the help are in sync with what Vieb actually recognizes as countable).

As for ideas to make it onto this cheatsheet, I would at least briefly mention all the different modes and their basic function. I think at least all the things from the `intro` chapter of Vieb's help should be listed. And finally all the things you suggested are nice to mention as well, and don't forget about window splitting (`:h splitting`).

**Comment by ottopiramuthu** [comment]
Here is a cheat sheet that fixes all of your bullet points:
![image](https://user-images.githubusercontent.com/49997309/121365365-96af7500-c906-11eb-8198-6a2a1d604193.png)

I plan on having sections for all the special modes and a short description of the mode under the headings:
```
Follow mode
-------------
Follow links on the 
page by typing keys
-------------
(the mappings...)
```
Let me know if you want any changes so far. I will continue adding mappings in the meantime.

**Comment by Jelmerro** [comment]
This is really starting to look great, thanks for making this a reality! Besides adding more info about different modes, I also would like to see some more split related mappings (I think the rotating and resizing mappings should at least be there). Currently the most obvious thing that is missing is a fair selection of commands, both splitting related (such as buffer or hide), but also about devtools, colorscheme, mappings (though this is already briefly mentioned) and settings. Overall, great improvement since the last version!

**Comment by Jelmerro** [comment]
That sounds great. Some of the commands that aren't mapped are still really useful, such as the colorscheme command, so it would make sense to include it I think. Most if not all splitting actions are mapped by default though, such as rotating or resizing, but not the commands like buffer and hide, which I think should also be listed for completeness.

**Comment by ottopiramuthu** [comment]
Here is a fairly complete cheatsheet based on your suggestions:
![image](https://user-images.githubusercontent.com/49997309/121414510-b52c6500-c934-11eb-932d-266840f4050a.png)
I've left space under `Pointer Mode:` for the download mappings, but I'm not sure if I can fit all of them. I also have to figure out how to concisely write down the different kinds of `map`pings.

Let me know if you want anything changed.

**Comment by Jelmerro** [comment]
This looks really good, you are really putting a lot of effort into making this, and it shows, thanks!

The download mappings actually follow a pattern for the first and second key that is explained in `:help link-related`. Maybe we could use a table to show them for type/action so the rows represent the media type and column the action, and you show the two keys in the table?

There are also new actions and menu options for interacting with media, all of them in pointer mode and they are prefixed with `m`. They are not listed in the help, it seems I didn't write docs for them yet, but I'll do so soon. When pressing `m` in pointer mode you will see them suggested by the new `mapsuggest` suggestions.

Also, the set command actually uses `=` as the separator, and can `setting=value` can be provided multiple times. There are more options than just setting values with it (such as reading `?`, toggling `!` and resetting `&`), and it seems like you have enough space below it to show more of the set command.

The actions related to the navbar are not countable, even though the help currently lists them as such. I'll update that shortly. It doesn't make much sense, because you would want to type out numbers instead of using them as a count for an action. This is my fault for not checking all actions after creating a new function for the countable badge based on the mapping system, instead of manually listing them as such.

The context menu can also be opened using `action.menuOpen`, which is by default mapped to `<c-m>`.

Finally one small question, did you create the image using the original SVG, or are you editing a PNG file?

**Comment by ottopiramuthu** [comment]
I'll respond to your points in more detail later, but I just wanted to let you know I am editing the ![original SVG](https://github.com/ottopiramuthu/files/blob/main/cheatsheet.svg). I'm not sure why github's preview isn't showing the bottom part, but you can tell by my exported PNG versions that everything is intact.

**Comment by ottopiramuthu** [comment]
I've added your suggestions except for this:
>  The actions related to the navbar are not countable

![image](https://user-images.githubusercontent.com/49997309/121496212-3ffa7780-c9a8-11eb-8580-00186ffa2cf3.png)

If you want anything changed let me know

**Comment by Jelmerro** [comment]
This is almost complete I would say, really detailed and in depth. I would consider to briefly mention that pointer mode will also hover the cursor at the current position, which can be good to know. Aside from that, I really can't spot any issues with this, great job!

**Comment by ottopiramuthu** [comment]
Once I add that, where do you want this in the repo? In the same directory as the README?

**Comment by Jelmerro** [comment]
One more thing I somehow overlooked in the last few versions, can we lowercase the keys that are supposed to be lowercase inside mappings (such as `<c-W>` to `<c-w>` or `<C-w>`, just not a capital `W`)? Only a bunch Control-based mappings seem to have this, other mappings are all ok.

I want to add this to the readme, but also use it inside the help page, so the file is probably best located at `app/img/cheatsheet.svg`. That we be perfect, we can show it in the readme right below the download section and also in the help page at a suitable located near the top to help new users. I might actually make a new page on the website that just shows the cheatsheet, it's that useful I think, it really captures most of the important points of Vieb in one image.

**Comment by Jelmerro** [comment]
I think we can close this ticket, since the readme, website AND the help page now include the awesome cheatsheet made by @ottopiramuthu
