### ISSUE TITLE
`:help` by mapping

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#214]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add support for searching the help page by mapping with `:help`. For example `:help gg` should open the help page to the action `gg` is mapped to. 

It would be nice if this followed Vim's syntax for modes.
For example:
- `:help <C-i>` goes to `#action.forwardInHistory`
- `:help i_<C-i>` goes to `#action.editWithVim`
- `:help p_f` goes to `#action.startFollowCurrentTab`
- `:help v_y` goes to `#pointer.copyText`
- ... and so on for the mappings in other modes

Some decisions to make:
- should Alt and Ctrl mappings follow Vim's syntax (`CTRL-I`) or use Vieb's syntax (`<C-i>`)
- where should mappings that execute multiple actions point to. For example, `vmap y` is both in `#action.toNormalMode` and `#pointer.copyText`. There needs to be a way to prioritize `#pointer.copyText`.

I'm open to any suggestions.

**Alternatives considered**
You can also search the help page (e.g. `/nmap gg`), but having this built into `:help` would make the help page easier to navigate for new users.

**Comment by Jelmerro** [comment]
The current alternative you describe is not ideal. You could just find which actions are mapped to a key by doing: `:map! gg` for example. And the same for a specific mode: `:vmap! y`. The function of `!` is different from Vim, in that it will show the default mappings as well, instead of saying "no custom mappings found". This is explained in the help page.

Though regardless of that being easier than the alternative you described, it's even simpler to directly open the help for a specific key. The examples you listed should all work when this is implemented.

Regarding your questions, I don't really feel the need for allowing `CTRL-I` when we already have `<C-i>`, which is shorter, easier to implement, simpler to explain in a mapstring and can do all things that `CTRL-I` can do and more. `<C-i>` is not actually Vieb's syntax, that will work just as well in Vim. I don't see an issue with the modes, you gave a few examples where you already solve this question: it will search the modes one by one for an action, and if prefixed it will search that mode only. As such, the example of `:help y` will go to `action.pageToClipboard` and not to `pointer.copyText` unless prefixed with `p_` like so: `:help p_y`.

**Comment by ottopiramuthu** [comment]
> The current alternative you describe is not ideal. You could just find which actions are mapped to a key by doing: :map! gg for example.

Good to know. Thanks for the tip!
> I don't really feel the need for allowing CTRL-I when we already have <C-i>, which is shorter, easier to implement, simpler to explain in a mapstring and can do all things that CTRL-I can do and more. <C-i> is not actually Vieb's syntax, that will work just as well in Vim.

I'm fine with that; it's more consistent with the rest of Vieb.. though I don't think this works in Vim. For example when I do `:help <C-a>` in Vim, I get the help page for `c_CTRL-R_CTRL-A`. 

>  don't see an issue with the modes, you gave a few examples where you already solve this question

My issue wasn't with modes, it was with mappings that use multiple actions. For example, `nmap E <action.openNewTab><action.toExploreMode>` uses two actions that have separate sections: `<action.openNewTab>` and `<action.toExploreMode>`. With `:help E`, you then need a way to decide which section this takes you to (`#action.openNewTab` or `#action.toExploreMode`).

**Comment by Jelmerro** [comment]
The help pages of Vim don't really use this syntax all that often indeed, but it is supported in Vim's map commands. If we were to add `CTRL-a` support to Vieb, should it only work on the left side of the map command?

I think in that case we should just pick the first action, in which case you can see that the key has more actions mapped to it. You can then use the help with that action name to find help for that. Creating a system to scroll through these or select them after typing a specific key that has multiple actions might make things a bit too complex, while I think the whole point of this feature would be to make it easier to find an action for a key.

**Comment by ottopiramuthu** [comment]
>  If we were to add CTRL-a support to Vieb, should it only work on the left side of the map command?

Sounds good to me.

> Creating a system to scroll through these or select them after typing a specific key that has multiple actions might make things a bit too complex

I agree. Picking the first action seems like it would be the least confusing way to handle this for a new user.

**Comment by Jelmerro** [comment]
Is it actually possible to make a mapping with that syntax at all that looks like this: `a<c-w>a`? That would result in `aCTRL-wa`, which really doesn't seem easy on the eyes. I have tested this in Vim, and it doesn't seem to work like that. It expects you to type out `a C T R L - w a` in that case. I even tried a mapping with `nmap CTRL-a :test` and it still expects me to type `C T R L - a` in order instead of understanding I mean `<C-a>`. So in response to that I don't think you can actually use that syntax in mappings, I know I have never used it before, and I see no further reason to add it to Vieb. That keeps things simple and consistent.

I will work on the original feature request of this ticket, because I think directly finding an action on the help page by a mapping can be really useful for (new) users.

**Comment by Jelmerro** [comment]
Let me know if the latest update (of the source code) works as expected in relation to this feature.

**Comment by Jelmerro** [comment]
Implemented in the latest release 5.1.0 release.
