### ISSUE TITLE
Allow mapping single-presses of modifier keys

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#221]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Allow mapping single-presses of modifier keys .
For example, you would be able to map:
```
fmap <Shift> <reorderFollowLinks>
```
so tapping `<Shift>` while in follow mode would reorder the links.

This would add the following keys:
- `<Shift>`
- `<Ctrl>`
- `<Alt>`

**Alternatives considered**
I couldn't find any alternatives.

**Comment by Jelmerro** [comment]
There is an existing setting for defining modifiers, you can read about it here: `:h modifiers`. This controls which keys are not registered on their own as keys. If you remove them from the list, they will not lose their modifier function, but they might interfere with multi-key mappings such as `<c-w><c-o>` or similar. This is because your keypresses will then be registered as `<Ctrl><c-w><Ctrl><c-o>`, the second Ctrl will cancel `<c-w>`.
