### ISSUE TITLE
Named registers

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#237]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add named registers from Vim. This includes `"[a-z]` to overwrite registers, `"[A-Z]` to append to registers, and `<C-r>[a-z]` to paste the contents of a register in all the modes that handle text.

**Alternatives considered**
Sometimes one clipboard is not enough.

**Comment by Jelmerro** [comment]
I don't really see much use for this, because "all the modes that handle text" are the following:
- Insert (which is very difficult to actually make this work for, and you wouldn't be able to type `"` if we were to add this)
- Command, search and explore mode (same issues as above)

The only reason registers work logically in Vim is because you aren't inserting text at the same, which (while also a goal of Vieb) isn't actually the same for Vieb, because there are many places on the page and the navbar that accept input, instead of just a text buffer. So in order for it to be clear "where" to edit, you need to be focused on it. It would be very unclear "what" exactly you would be copying if you could do this from normal mode in Vieb: would it be the url? the last command? the previous search? the last focused input field? the first input field? What I'm trying to say is that there is a point where trying to copy over EVERYTHING that Vim can do stops working in the context of the web, I think this is one of those cases. Aside from that, you already can edit all of the modes with text input using your favorite editor, so there wouldn't actually be much use for this anyway, as editing in Vim will ALWAYS be superior compared to editing text in Vieb, or any other project for that matter (maybe excluding neovim etc., but that is beyond the scope of what I'm trying to say with this).
