### ISSUE TITLE
Enhancements to `:colorscheme`

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#239]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
- `:colorscheme&` to use default colorscheme
- `:colorscheme?` to show the current colorscheme in a notification (useful when you have very similar schemes and need to know which one is applied)

**Alternatives considered**
`:colorscheme default` works, but there is not alternative to `:colorscheme?` as far as I know.

**Comment by Jelmerro** [comment]
This is clearly explained in the help at `:help colorscheme`, it's not configured with the set command, but it does support the use cases you describe. Reverting to the default colorscheme is done with `:colorscheme default`, it's the only name that cannot be used by other themes, so there is no confusion what `default` refers to, it's always the basic Vieb styling. Showing the current theme is done by running `:colorscheme` without arguments. If you really wanted to, you could define custom commands to do what you describe:

```vim
command! colorscheme& <:colorscheme default>
command! colorscheme? <:colorscheme>
```
This is possible, because for now the only trailing character that is recognized for commands as the same command is `!`, so `colorscheme&` is actually a separate command from colorscheme (and you can't override default ones).

It won't be added like that as it's not how it's implemented in Vim, and I'll close this ticket and leave it up to you to customize your Vieb like this, as it is already possible to set, read and reset the colorscheme the same way you can in Vim.
