### ISSUE TITLE
Support XDG

### ISSUE THREAD

**Issue by samhh** [Jelmerro/Vieb#244]
At the moment, on Linux, `~/.config/Vieb/` is where all data is stored. In order to support the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), Vieb should instead:

- Store most data somewhere else, for example under `$XDG_DATA_HOME`
- Respect `$XDG_CONFIG_HOME` for configuration (defaulting to `~/.config/` as now)

**Comment by Jelmerro** [comment]
You can change the datafolder with `VIEB_DATAFOLDER` or the `--datafolder` argument. Spreading the data over multiple folders would hurt the portability of Vieb, and having to explain yet another way to configure this would make the startup help less easy to understand. I think portability and simple ways to change this are more important than following every spec out there. Besides, `XDG_CONFIG_HOME` is already respected by Vieb, it's just not explicitly mentioned as such, but only referenced as `~/.config` in the docs.

**Comment by Jelmerro** [comment]
I just noticed your reaction on my comment, which suggests my response was very clear, so I'll summarize it based on the two main points you suggested:
- You can configure where you want to store the data with the datafolder startup option, see `:h datafolder` for details, Vieb uses a single folder for storing data to keep things portable and practical
- The `$XDG_CONFIG_HOME` is already respected by Vieb, it's just that the docs list it as `~/.config` since that is what most Linux systems use by default for that folder

Vieb will be keeping the single datafolder structure for practical reasons, but you can already choose which folder you want the data to be stored with `$XDG_CONFIG_HOME` or the more extensively documented `:h datafolder`.

I'd much rather see a proper reply as to why you were confused by my response instead of a single reaction emoji, so we can discuss the issue. In other words, why do you think that the benefits of following XDG spec outweigh the downsides of no longer having a single datafolder that is portable?

**Comment by Jelmerro** [comment]
I just noticed your reaction on my comment, which suggests my response wasn't very clear, so I'll summarize it based on the two main points you suggested:

- You can configure where you want to store the data with the datafolder startup option, see `:h datafolder` for details, Vieb uses a single folder for storing data to keep things portable and practical
- The `$XDG_CONFIG_HOME` is already respected by Vieb, it's just that the docs list it as `~/.config` since that is what most Linux systems use by default for that folder

Vieb will be keeping the single datafolder structure for practical reasons, but you can already choose which folder you want the data to be stored with `$XDG_CONFIG_HOME` or the more extensively documented `:h datafolder`.

I'd much rather see a proper reply as to why you were confused by my response instead of a single reaction emoji, so we can discuss the issue. In other words, why do you think that the benefits of following XDG spec outweigh the downsides of no longer having a single datafolder that is portable?

**Comment by samhh** [comment]
Hey @Jelmerro,

Sorry for the emoji reaction, that's lazy and rude on my part. It's been a long month.

I was disappointed to discover that, for unrelated reasons, Vieb probably doesn't fit my use case. Disappointed particularly given how very well polished it is, and how performant it is compared to the likes of vimb. It's a credit to the software that even then I've kept it installed and a manicured config available for further tinkering.

With respect to XDG, I think sticking everything in a single directory _reduces_ portability and makes the system less practical to use. If someone anticipates for example that all their application caches live in `$XDG_CACHE_HOME`, it will be surprising to find that for Vieb that's not the case. Likewise, if someone wants to quickly zip up their `$XDG_CONFIG_HOME` and pop it onto a new machine, perhaps by uploading it somewhere, they might be surprised to find that Vieb's configuration directory takes up so much space. They then need to manually work through the directory to understand what's actually configuration and needs keeping.

I'd argue that a better approach to portability would be an external tool or library that can collate all the same-named directories amongst XDG directories and then spit them back out again appropriately. Failing that there's always symlinks. I'm not sure how many users need drag and drop portability like this, particularly for a single app, but it breaks reasonable assumptions users like me have come to make about their system.

In the interest of fairness, _a lot_ of apps don't support XDG, and even fewer support it out of the box without explicit configuration. But I think thankfully the wind is moving in that direction, particularly if you exclude old, ingrained software for which it'd be a major breaking change.

Thanks for your conscientious reply,

Sam

**Comment by Jelmerro** [comment]
I can only speak from experience of developing Vieb and Electron apps on this (as my other apps usually don't store that much data), but it actually takes effort to comply with XDG, it's definitely not out of the box (for Electron apps). I wouldn't even know without searching the docs if having a separate cache folder is even supported. So I just checked, and it's still very much a problem that you aren't able to set the cache directory separately in Electron, so since Electron is nowadays used for a lot of apps, I don't think the XDG spec is actually supported by as many programs as one would hope. See [these issues](https://github.com/electron/electron/issues?q=cache+directory+custom+path+is%3Aopen) to see it's not even possible, also including this comment from one of the Electron devs:
![image](https://user-images.githubusercontent.com/1696674/123336329-013af480-d546-11eb-9878-45909275787a.png)
So this actually goes much further than just Electron apps. It's for every app that uses Chromium as the base that following the XDG spec (at least regarding cache) just isn't possible, unless you manually move files around with a wrapper script or a similar hack.

This standard not being followed is also my experience actually, since most programs I use either dump a folder in my home directory or just use `.config` and `.local/share` for all their data. And if they use `.cache` it's most of the time only for temporary stuff, not for browser data (and if they do, only for browser cache, not the other stuff).

This combined with the fact that by default Vieb even clears the browser cache on quit, I doubt that there would even be a use for a separate cache location for Vieb. What kind of data would you move from the current datafolder to a potential cache folder? I personally can't think of much besides browsing cache, which (as mentioned) is cleared by default anyway.

Also, could you elaborate on the "unrelated reasons" in which Vieb "doesn't fit your use case"? Is this something that already has an open issue and/or you are willing to share?

**Comment by samhh** [comment]
I was tempted to say in my previous comment that the JS ecosystem is one of the largest holdouts with XDG, I suspect because many of its devs are on macOS rather than Linux. I raise issues about XDG semi-regularly and it's really the only ecosystem that in my experience doesn't embrace it.

Electron is a major culprit. If I look in my config dir all the largest offenders are Electron-based, such as Slack. [This](https://github.com/electron/electron/issues/8124) issue exists to track XDG support for cache data, and [this](https://github.com/electron/electron/issues/8124#issuecomment-832252443) comment expresses quite well the problems that can arise with the current approach. Alas I think it's out of scope for Vieb specifically.

My other issue, more pressing, is the desire for multiple windows. I run a TWM and prefer to treat my browser as not supporting tabs/buffers/etc, instead delegating that responsibility to my WM. I _think_ the current state of Vieb doesn't support this per [this](https://github.com/Jelmerro/Vieb/issues/141) issue.

**Comment by Jelmerro** [comment]
I understand your response and also think this is a much broader issue than just Vieb specifically. This combined with the limited amount of cache Vieb stores by default suggests to me that closing this issue was the right resolution, at least for the foreseeable future. If/when Electron fixes this I will check if Vieb has by then a lot more things it will be caching, but I doubt that it will be much beyond the autoclearing browser cache that we have today.

Regarding the multiple windows, they are supported just not when using the same datafolder, which is indeed a problem tracked in that issue. This will require a significant rework in how data is handled in Vieb to work and it will also need to sync that between windows (it won't make Vieb faster, that's for sure), for now all urls/files opened are redirected to the existing instance in that folder and you can only have one running instance per folder. You can however open new windows if you open a new instance in a separate datafolder, which means they won't share any data. I think this can work for many of the use cases where people normally use multiple window setups for, but this probably won't work nicely for your setup. The best I can think of is writing a wrapper that makes a new instance based on the domain you will be opening, so that you can share data between those and have many windows open, but one for each domain or something along those lines, or alternatively using many separate [Erwic](https://github.com/Jelmerro/Vieb/blob/master/Erwic.md) instances to open a fixed set of tabs/pages per instance and just keep it at that.

**Comment by samhh** [comment]
I'll keep tracking the aforementioned issue. Appreciate the replies and your work on Vieb!
