### ISSUE TITLE
Security questions

### ISSUE THREAD

**Issue by asmallcarrot** [Jelmerro/Vieb#268]
I was checking the electron security page [here](https://www.electronjs.org/docs/tutorial/security) and read

> When working with Electron, it is important to understand that Electron is not a web browser. It allows you to build feature-rich desktop applications with familiar web technologies, but your code wields much greater power. JavaScript can access the filesystem, user shell, and more. This allows you to build high quality native applications, but the inherent security risks scale with the additional powers granted to your code.

All websites can access file storage which is extremely dangers, are there any mitigation's that have been implemented?

Edit I ran browser audit on it to look for some basic vulns, the results are pretty bad 63 critical. Compared to only one on brave (appears to be a false positive). I love the project but something needs to change.

**Comment by Jelmerro** [comment]
This is greatly exaggerated and simply isn't true in Vieb's case, because the text above is talking about the renderer process. The websites run a layer deeper in webviews, which don't have the same integration. Basically the layers in Vieb are as follows:

- Main - Full access to everything, does not run any user code or import separate files. It will load a local html file that doesn't have nodeintegration and only loads data using a preload. This process and most of Vieb and it's GUI run there, which is the renderer.
- Renderer - This is where most of VIeb's code is, which gets loaded as a preload script from the main thread. Note that the content security policy of the index.html does no allow other scripts to be executed. In the preloads the initial setup and background processes of Vieb will run, some of which will create the final layer of Vieb: the webview.
- Webview - This is where the actual pages are loaded.

**Comment by Jelmerro** [comment]
I would like to know what tool you ran to check for vulnerabilities, last time I ran [Electronegativity](https://github.com/doyensec/electronegativity) I found around 10, most of which required manual review, such as the permissionhandler, permissioncheck (which is just e.preventDefault) and the webview on-create handler etc.

If you could post the list here, we could better discuss the specifics of potential vulnerabilities instead of desiring specific flags to be enabled. I believe there are other ways to secure an Electron application in the meantime, until we can enable sandboxing without destroying the application and webviews.

What I want to ask of future security tickets, is that they can be demonstrated or at least explained to be a current issue for Vieb. I will explain what I mean with that with two fictional examples: a good example and an example we can't use to actually achieve much additional security:

### Example of a non-issue, one which cannot be made actionable

- "Please enable sandboxing, you are exposing the entire filesystem to every website"

As I explained above, this isn't the case for Vieb, and we also can't enable sandboxing to fix this. While this issue highlights a setting that could be used in the future, it doesn't go into detail why/if the entire filesystem is really exposed, and that's because it isn't. We also can't actually bring this request to action, because there is no explanation of where the file system would be exposed. To make this actionable, I would prefer issues to regarding security to look like this:

### Example of an actionable issue, that explains where/why a problem exists

"In the follow.js preload of the webview, you expose function x which could be used to gain filesystem access, it would be better to proxy that differently"

This shows an actual problem that can be worked on, one that can be discussed and solved. It doesn't assume there is only one way to secure an app, and also shows there was more research done than merely running a tool and concluding that every app is insecure because there are more than 0 reports. It's all about being specific about what these issues entail. If you also used electronegativity I can assure you that over half of those require manual review or are fundamentally unfixable because we are using webviews. I would like to ask you to post the list here, because I am really curious what kind of things are listed in those 63 entries.

**Comment by asmallcarrot** [comment]
I ran browseraudit.com
The main issues are in the SOP. 
I'm currently working on some proof of concepts.

**Comment by Jelmerro** [comment]
Those can be fixed by running vieb with `--site-isolation=strict`, but that does mean that iframes will lose most of Vieb's functionality. Sadly we need to relax the isolation policy for that, because of [this missing Electron feature](https://github.com/electron/electron/issues/22582). I don't have the required C++ knowledge to make it myself, but the reason you get those SOP errors are because of this workaround that you can disable with the startup argument I mentioned above. There are enough [open issues in the Vieb project](https://github.com/Jelmerro/Vieb/issues/179) that relate to that missing feature, so I'm going to close this one for now (combined with the comments of my previous comments).

**Comment by asmallcarrot** [comment]
Thanks for the info! One thing I did find is that cookie's set by javascript with the Secure flag should be sent over HTTPS (was sent over HTTP)

**Comment by Jelmerro** [comment]
That can actually be reproduced in Edge (Windows) and Chromium (Linux/Windows) so it seems to be a Chromium issue, as Vieb is just Chromium of course. So I would recommend to open a Chromium issue for that :slightly_smiling_face:
