### ISSUE TITLE
Got Any Performance results to compare it to Other Browsers?

### ISSUE THREAD

**Issue by pegromdev** [Jelmerro/Vieb#269]

**Comment by Jelmerro** [comment]
I don't, because I don't mind the performance. For me the performance of a browser is not a major reason for choosing it over the other, if it's not bad enough to notice. That said, there is one known performance issue, which is related to an iframe timer workaround. You can read about it [here](https://github.com/Jelmerro/Vieb/issues/179). I personally don't run into this issue often, as I tend to avoid bulky sites like youtube. Besides that, the performance of Vieb is pretty decent as far as I'm concerned, though there is always room for improvement. The most notable would be the startup speed, for which there is [also a ticket](https://github.com/Jelmerro/Vieb/issues/66). Note that I don't plan to pick up either of those any time soon, because I'm not a performance expert, I don't mind the current speed and also because the first issue mentioned is actually a workaround for an Electron issue, which requires changes upstream to be improved.

Hopefully this answers your question, if not, we can continue to discuss it below, I'll close it as your concern seems mostly represented in those two issues. Regarding an actual performance comparison/chart, feel free to make one and share it [on github discussions](https://github.com/Jelmerro/Vieb/discussions) or on [the subreddit](https://reddit.com/r/vieb/).
