### ISSUE TITLE
Use vim commands for handling tabs

### ISSUE THREAD

**Issue by Silur** [Jelmerro/Vieb#270]
Tabs are not bound to standard vim commands as of now - `t, d, w b`. It'd be nice to support the standard vim commands for handling tabs: `:tabe <file/URL>` to open a tab, `gT` and `gt` to switch tabs and `:q` to close a tab.

**Comment by Silur** [comment]
found out that `gT` and `gt` works by default, and for now mapping `tabe` to `openNewTab` is a quick solution

**Comment by Jelmerro** [comment]
`gt` and `gT` are already there, I just preferred single character keys for the intro section, as you correctly noted.

Instead of `:tabe`, there is a separate mode for navigation named Explore mode. This was done because it's such an important part of a web browser, that it made sense to give this more flair and realtime suggestions with colors and icons. Pressing `e` to navigate is actually in line with a couple of other Vim browser plugins, so I'm luckily not the only project/person thinking this :wink:

The `:q` command is there. The difference of `:q` is that Vieb will quit if there are multiple tabs, because tabs in Vieb are more of a browser thing than an actual Vim tab implementation. However, the `:q` command will close the current split if you are using window splits, similar to Vim. Vieb aims to bring a similar experience to the web, not one that is identical just for the sake of it. I have experimented with making tabs more close the Vim, and each time it felt unnatural to do so in a browser context. This is why I decided to only make splits work identical and let tabs be relatively close to regular browsers. In case you feel that it should be more close to Vim, I encourage and welcome PRs, but for now I will consider this question answered.
