### ISSUE TITLE
Some links aren't visible when pressing f on nitter.net

### ISSUE THREAD

**Issue by vinliao** [Jelmerro/Vieb#284]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Some links aren't showing on nitter.net
![Screenshot from 2021-08-28 21-34-21](https://user-images.githubusercontent.com/34117807/131221988-fd898b51-730c-49a9-8cf0-7bd750f693ad.png)

See the top tweet over there? There's a link for that box, but there's no link for the box below it. Every tweet is clickable.

Temporary solution: click on the date and it will go to the tweet (in the example above, for instance, just press Q).

**To Reproduce**
Go to nitter.net, then press `f`. Some tweets can be "clicked," some can't.

**Expected behavior**
All tweets should be "clickable" when pressing `f`.

**Specs**
 - OS: Fedora 34
 - Version: 5.3.0 (Latest)

**Comment by Jelmerro** [comment]
This is actually a nitter bug, I'll explain why that is the case.

Those tweets also aren't clickable with the mouse, also not in other browsers, nothing happens if you click the text, but you have to click on the top bar or the retweet count section at the bottom. You have to specifically pick a section of the tweet where there is no text to be able to click on it. Because some tweets have text in the center of the tweet, while others do not, it could seem a bit random that some tweets are clickable with follow mode while others aren't, but this is caused by the text being unclickable, not by a Vieb bug.

The reason the text isn't clickable is because there is a `pointer-events: all` on the `.tweet-content` css class, which in this case is the tweet body text. This sounds nice on paper, but if you do that inside an anchor link tag (which the entire tweet is), you won't be able to click the link, but instead of that you will interact with the text. The `pointer-events: all` causes this to be the case: you no longer interact with any parent, but instead you will execute ALL pointer events on this `.tweet-content` element, which only contains a bunch of text in most cases, but not all. You can find the problematic source code [here](https://github.com/zedeus/nitter/blob/master/src/sass/tweet/_base.scss#L22) in case you are interested and/or know how to use CSS.

I would recommend to make a bug in the [nitter repo](https://github.com/zedeus/nitter/) instead of here, as this isn't a Vieb specific bug: it happens in all browsers because of the `pointer-events: all` being set on the text. Feel free to link this issue when making one in the nitter repo so they know how to fix it.

**Comment by vinliao** [comment]
Thanks. I've posted an issue on the nitter repo about unclickable tweets months ago. Maybe I can bump the issue again.

And thank you for creating Vieb. It's such a nice browser to use. I'm delighted.

**Comment by se7en-x230** [comment]
I have a similar problem at github.
It worked 2 versions back as far as I recall.

![image](https://user-images.githubusercontent.com/69777713/133023915-145a6d95-9afc-4ca4-af84-353d298854c3.png)

**Comment by Jelmerro** [comment]
Which links are you missing in this example? Because this looks like the newtab version of follow mode, which only shows links that can be opened in a new tab. With the default mappings this is `F` instead of `f`. Can you confirm this is the case and let me know which of the links you are missing here?

**Comment by se7en-x230** [comment]
@Jelmerro confirmed. I have set f as open in new tab. If I reverse the settings to default all links show just as before.

Thanks for explaining that.
