### ISSUE TITLE
On some systems, the `<nextSearchMatch>` jumps randomly when called from pointer mode

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#287]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
The actions for jumping the pointer to the next search match do not do this, instead they seem to jump randomly:

https://user-images.githubusercontent.com/49997309/131497696-47afc5d3-70ec-44f1-be84-199250ef728d.mp4

**To Reproduce**
- `:help<cr>`
- `/vieb<cr>`
- `v`
- `n/N`
- pointer does not jump to the search match. It looks like the pointer is jumping randomly.

**Expected behavior**
The pointer should jump to next/previous matches of "vieb".

**Specs**
 - OS: Windows 10
 - Version: Vieb 6.0.0-dev

**Comment by Jelmerro** [comment]
In all honesty, the Electron API for this is a mess, so we need a lot of code around it to detect the position of the search element on the page. For example, the automatic scrolling can happen either before or after returning the next search result. I hope the new implementation takes this into account properly and gives the desired results. Let me know if this is better.

**Comment by ottopiramuthu** [comment]
I see how this can be hard to track. Unfortunately, I'm still getting similar pointer jumping with the latest commit.

**Comment by Jelmerro** [comment]
I just tested this on a Windows machine, and even there it works surprisingly well. I'm wondering what could be the problem on your system. Can you reproduce it with the default theme as well? Because it looks to me like the pointer is offset from the expected position, since it does seem to move left and right similarly to the results being highlighted. Could you perhaps share your theme file and output of `:set` here?

**Comment by ottopiramuthu** [comment]
I've tried it with the default colorscheme and sill get the offset.
- [my theme](https://gist.github.com/ottopiramuthu/8c1363fe27439dfd45d95abb598e0eef)
- [output of :set](https://gist.github.com/ottopiramuthu/cf61496a371b7a13f487e3511c1415d6)

**Comment by Jelmerro** [comment]
So a couple of things that are also NOT related to this bug:

- Fontsize, which I kind of expected it to be after seeing it in your options list, but even so it works as expected with different sizes (on  both Windows & Linux)
- Theme, works when using the provided theme file, I also tested the flipped theme while I was at it, works as expected (both Windows & Linux)
- Any of your other settings are also not causing me to have the issue here (again, on  both Windows & Linux)

I am running out of things to try here, if you know of anything else it might possibly be, please let me know. At least we know it's a rare case for it not to work, whatever the cause for it may be.

**Comment by Jelmerro** [comment]
Just for my confirmation, are you still having this issue in 6.1.0 @ottopiramuthu?

**Comment by ottopiramuthu** [comment]
Yes, I still have this with Vieb 6.1.0.

**Comment by Jelmerro** [comment]
I still have absolutely no clue what could be causing this as it works in so many scenarios and configurations here, regardless of OS or zoomlevel. If you ever find any clues that could relate to this bug, just let me know.

**Comment by Jelmerro** [comment]
I can now finally reproduce this issue, and it seems to be because the Electron API is not consistent in returning the position before or after scrolling. The existing workarounds for this only worked because on my machine, it used to always happen in the order of: the element position is returned after scrolling, then the scrolling happens. This is the ideal scenario, and doesn't require any further calculations. However, it can also return the element position before scrolling, then scroll OR in some scenarios: scroll first, and then return the element position before the scrolling, which is confusing to say the least. I have made some changes in [this commit](https://github.com/Jelmerro/Vieb/commit/dc9923f3196e415127197184c277a7f6f7c99db2) to consider all three scenarios, with which I have hopefully also fixed this issue. Looking forward to hearing from you, as this has been an issue for far too long.

**Comment by ottopiramuthu** [comment]
Sorry for dropping off for so long, I got very involved with other projects.
I've been having trouble building the commit in question through npm because of some error with the adblocker.
![image](https://github.com/Jelmerro/Vieb/assets/49997309/bb05e99b-83ae-4a3a-b563-7f9e65cabf3b)

I could, however, test the 10.0.0 release, and I get a similar, but more promising error. Whenever the pointer is going to results that are completely on the screen it is in the correct place. Once it needs to scroll, the pointer is offset in the y direction, but is in the correct x position from then on.

**Comment by Jelmerro** [comment]
That is also the issue I had in V10, but that is what led me to figure out what was going wrong, hence that I tried to fix it once more in that commit. Don't worry about not responding for a few days/weeks, I occasionally do the same, but there's no rush :wink: What version of npm are you using? I'm on version 9.7.1 and it's working here, even after clearing the node_modules, which you could also try first. If you are not using the latest npm, either update via your package manager or run `npm -g i npm@latest` to update npm with npm.

**Comment by ottopiramuthu** [comment]
After updating npm that commit fixes it! Thank you for sticking with this issue for so long :)
