### ISSUE TITLE
Allow features of the mouse to be individually enabled or disabled using a list-like mouse setting

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#291]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Scrolling the pointer to the top of the page in fullscreen will reveal the nav/tabbars if `guifullscreentab/navbar` is set to `onupdate`. According to the documentation, this should only happen when tabs are changed.

**To Reproduce**
- `:help<CR>`
- `<F11>`
- `v`
- `j` for a bit
- `k` until you hit the top of the page
- whenever the top of the page is hit, the tab- and/or navbar (whichever ones are set to `onupdate`) are shown for `guihidetimeout` seconds.

**Expected behavior**
The tab/navbars should not be shown when the pointer is moving, only when tabs are updated.
**Specs**
 - OS: Windows 10
 - Version: Vieb 6.0.0-dev

**Comment by Jelmerro** [comment]
I'm not sure if this is a bug actually, because if the mouse is enabled you can always move the mouse to the top to reveal the interface if it's not disabled, but maybe some extra checks for what kind of UI is enabled are missing there. I'll double check if everything is as expected and update the docs accordingly, but my suspicion is that this is working as expected (since pointer is just a mouse cursor for the page).

**Comment by ottopiramuthu** [comment]
> (since pointer is just a mouse cursor for the page).

I would mention this more explicitly in the docs. Maybe in the opening paragraph for `:h pointer`.

Would it be too much to have a setting to toggle this behavior of the mouse/pointer? When I set `onupdate` for `guifullscreentab/navbar` I really only want the tabs/navbar to show up when changing the tabs to minimize distractions.

**Comment by Jelmerro** [comment]
It's actually more related to the mouse than to the pointer, so would it also be fitting to explain it there? I was also thinking or reworking the mouse toggle into a list-like setting to enable specific mouse functionality instead of being required to set all or nothing in terms of mouse actions. What do you think of this?

**Comment by ottopiramuthu** [comment]
> It's actually more related to the mouse than to the pointer, so would it also be fitting to explain it there?

Yes, that makes sense.

>  a list-like setting to enable specific mouse functionality

I agree with this. If you have the option through electron to control the mouse this way, it's better to give the user similar control.
