### ISSUE TITLE
Settings not saved between sessions

### ISSUE THREAD

**Issue by slzatz** [Jelmerro/Vieb#300]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer a github issue over asking my question on [r/vieb](https://www.reddit.com/r/vieb/)

**What needs to be solved**
The problem is simple: no settings are being saved between sessions
**Steps that have been attempted**
It's not obvious where information like favoritepages are stored but the sequence is 
1) create a favoritepage entry.  I can see it in the current session when I open a new tab
2) When I quit vieb and re-open the favoritepage I set is gone.  This is true of all settings.  

Since I have not seen this issue I am wondering what is different about my setup but it is just plain arch with vieb installed from the AUR and everything works fine except that nothing is saved between sessions.

**Comment by Jelmerro** [comment]
This is exactly how it's supposed to work: It's explained right at the top of the settings chapter, see `:h settings`. Basically, settings are only changed at runtime unless you choose to save them to disk for next sessions with `:mkviebrc`. You can also edit the settings file directly if you want to, even when running Vieb, because it doesn't get modified or re-read without you knowing (which you can do with `:reload`). Let me know if you still have questions not answered here or in the help, or even make a PR to improve the settings chapters :wink:

**Comment by slzatz** [comment]
Thanks for the instant reply and sorry for the noise.  It's an unusual (but completely sensible) approach to managing user data:

Not brilliant suggestion would be in your high-level bullet points:

Viebrc config file for all custom/Vim/Vieb commands where you can edit/save settings permanently or update with current settings with mkviebrc command.

As an aside, I think vieb is a terrific improvement on standard browsers (now that I know how to save settings!)

**Comment by Jelmerro** [comment]
Glad you figured it out, I'll double check the wording to make sure it's consistent and explicit about this in the app and in the readme. The settings are mostly modeled after Vim, which also has runtime only set commands unless saved to disk with `:mkvimrc`. Oh, and the keyboard mappings and custom commands are also stored in the viebrc file.
