### ISSUE TITLE
AUR vieb-bin

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#302]
What happened to the AUR vieb package?

I can only find vieb-bin. 
Is that now the official version?

**Comment by Jelmerro** [comment]
I'm not in charge of any third-party package: I maintain the github repository, the github releases and the official website at [vieb.dev](https://vieb.dev) (the download page also links to the github releases). The third-party releases are just that: releases made by a third-party. That sounds a lot scarier than it is, as this is in fact the case for most of the packages on your system, which is because it's way too much work to distribute an app to all the different distributions for a single person.

Having said that, it seems from the AUR comment section that the vieb package wasn't deemed necessary due to the frequent stable releases of Vieb, and has been merged into vieb-bin:
![image](https://user-images.githubusercontent.com/1696674/132718514-09d1e949-0109-431a-96be-c906c1811a0a.png)
You can see it live and discuss this change at the [vieb-bin AUR package webpage](https://aur.archlinux.org/packages/vieb-bin). I don't even use Arch myself, so frankly this doesn't concern me, but I'm happy to answer any questions related to Vieb :wink:
