### ISSUE TITLE
Rectangle selection for screenshots

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#304]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Screenshots based on rectangle coordinates (x, y, width, height).
Since `capturePage` offers a [rect argument](https://www.electronjs.org/docs/api/web-contents#contentscapturepagerect), it would be nice for Vieb to have similar arguments for `:screenshot`.

**Alternatives considered**
Taking a normal screenshot and cropping is relatively tedious.

**Comment by Jelmerro** [comment]
If you could come up with a nice command syntax for it, I don't mind implementing this, but I'm unsure what would be a sensible way to do this. Maybe detect which argument means what if there are multiple and provide them like `240x100 ~/image.png` or something?

**Comment by ottopiramuthu** [comment]
I was thinking detecting which argument is which as well. Different screen capture tools on Linux have different ways of specifying the rectangle. Qutebrowser and [maim](https://github.com/naelstrof/maim) use a format like `wxh+x+y`. Maybe to make this look more like a Vieb setting you could use something like `w,h,x,y`. Let me know if you have any other ideas.

**Comment by Jelmerro** [comment]
I initially thought of embedding this in the screenshot command arguments, but a setting for it could also work. What has your preference?

- Two optional arguments to the command, so it accepts any five of these variations: `:screenshot`, `:screenshot <location>`, `:screenshot w,h,x,y`, `:screenshot <location> w,h,x,y` or `:screenshot w,h,x,y <location>`
- A setting that will always be used by the screenshot command and only keep the optional location argument part of the screenshot command

I slightly prefer the former myself as it seems doable to detect which of the two arguments is the location and which is are the dimensions, and also because it keeps the configuration for the screenshot command in one place (we know there won't be other configurations for screenshots in the near future due to the Electron API giving us only these options). Finally I was thinking of giving the option of specifying a width and/or height as zero if you want to use the full width/height while still selection a region. What do you think?

**Comment by ottopiramuthu** [comment]
I prefer the first option. The screenshot command already has "default arguments" in the `:screenshot` case. A new user would assume both `<location>` and `w,h,x,y` are optional.

> specifying a width and/or height as zero if you want to use the full width/height while still selection a region

Yes, that would be nice.

**Comment by Jelmerro** [comment]
That's good to hear, glad we are on the same page. I'll try to add that in the weekend, which will hopefully also be the moment I finally find the time to do a full release again. I'm not sure if making the 0 act as full height/width is easy or even possible, but it seems like a nice feature to include if it is. I'll let you know when I start working on this via the assignee attribute of this ticket as per usual.

**Comment by ottopiramuthu** [comment]
Just tested this out on Windows and it works great. The rectangle indicator is super nice :)

**Comment by Jelmerro** [comment]
That's great to hear, I'll also be adding a similar command for copying the image to the clipboard name screencopy.

**Comment by Jelmerro** [comment]
This is included in the latest Vieb release!
