### ISSUE TITLE
Setting to open every tab in a new window instead

### ISSUE THREAD

**Issue by markstos** [Jelmerro/Vieb#322]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**

I would like to manage tabs using my window browser (Sway) which supports tab-grouping of Windows.   Qutebrowser supports this with an option named "tabs_are_windows:true"

https://qutebrowser.org/doc/help/settings.html#tabs.tabs_are_windows

When enabled, the tab bar is hidden and any command or binding that would open a new tab opens a new window instead.

**Alternatives considered**

   * Using tabs managed by the browser requires remembering one set of key bindings for moving and managing tabs in the browser and a second set of keybindings for managing tabs in the window manager. By making every "tab" a first class window, the experience is improved for tiling window managers. For example, there's often a way to search for a window by name to switch to. When every tab is a window, you can switch from another app directly to a specific "tab" in the browser in one step.

**Comment by Jelmerro** [comment]
I don't mind making this an option, but it requires #141 to be implemented.

**Comment by mentalisttraceur** [comment]
For the record, this is the main reason why I use Qutebrowser instead of Vieb as my primary browser. Actually the only reason that I can remember.

**Comment by Jelmerro** [comment]
Since #141 is now an option, this can be achieved by doing:
`:set containernewtab=s:external externalcommand="vieb --unsafe-multiwin=true --datafolder=<datafolder>"`
This does required the installed Vieb to have this setting as well, so it only works when installed not when run from source, I have yet to release this version. It's also recommend to have this setting in your viebrc, since it will not be synced between windows and thus only work in the first one if not read from the viebrc. Overall this approach has a lot of disadvantages to using multiple datafolders, which will remain the recommended way to create multiple windows, as per FAQ.

**Comment by mentalisttraceur** [comment]
Related to [my comment in #470](https://github.com/Jelmerro/Vieb/issues/470#issuecomment-1536696842) - I've never tried `--unsafe-multiwin=true` (assuming it's even available in a release build yet? haven't checked) because as I understood it, `--unsave-multiwin=true` creates risk of losing/corrupting stuff (which I presume includes history, what pages were open when the browser was last closed, etc).

And so long as history or open-tabs-when-browser-last-closed/session-last-saved is liable to be lost (at least until I have the time to look into some sort of alternative way to duplicate that information externally), that's just not something I'm going to gamble with. (If there was documentation about what kind of actions could cause what kind of corruptions, even if it's just super technical stuff like "whenever function foo is called, which is called from at least x, y, and z at this time - but check the latest code to be sure", I'd be more comfortable trying it.)

As is, if I can't get used to Vieb's single-window workflow, what I might be inclined to do is create multiple data dirs for when I want new windows, and if that stops scaling well, some simple program/script to create a new datadir copy (probably with a file-descriptor-based `flock(2)` lock on some constantly-existing file in the data directory, so that it vieb can just inherit that file descriptor (I sure hope it doesn't automatically close every FD it doesn't use at startup) and then it will get automagically unlocked by the OS if the vieb process exits with no need for coordination from within vieb).

(The ideal would then be if I could at least merge stuff like history and cookies from those working datadirs into some latest template datadir which no vieb ever uses but which gets updated each time one vieb closes... but that's a whole big undertaking I probably will never get around to doing.)

**Comment by Jelmerro** [comment]
The command above does exactly what you mention and will create a new window in a custom datafolder (a different one, but the same external one) when you open a page externally with `x` or other external commands. Regarding what will corrupt, most likely not much in the beginning, especially if you don't use the windows at the same time, but especially Chromium's storage such as sessionstorage, localstorage and cookies are very much not made to be used in multiple windows at the same time, and since that isn't supported, Vieb settings don't account for it either, though those are anyway stored in a single file per datafolder and don't update based on runtime changes, just don't expect the windows to stay in sync.

**Comment by mentalisttraceur** [comment]
That's not exactly what I am saying - I'm talking about accepting multiple datadirs for robust function and making it work reasonanly transparently from outside Vieb.

I'm basically imagining a script like this:

```sh
#!/bin/sh -
available=false
for directory in ~/my/vieb/datadirs/*
do
    exec 3<directory/my-dummy-lock-file || exit 1
    if flock -n 3
    then
        available=true
        break
    fi
done
if ! available
then
    directory=`mktemp -d ~/my/vieb/datadirs/XXXXXX` || exit 1
    cp -r ~/my/vieb/master-datadir/* "$directory/" || exit 1
fi
vieb --datadir="$directory" "$@" || exit 1
# if I can figure out how: merge datadir changes from
# $directory into ~/my/vieb/master-datadir - at least
# history and tabs saved before exiting would be cool.
```

**Comment by mentalisttraceur** [comment]
To be clear, I'm not saying Vieb should do anything here. I'm just saying that the way things are right now, this is probably what I would do the next time that I want fluently multi-window Vieb badly enough.
