### ISSUE TITLE
More instances than one ?

### ISSUE THREAD

**Issue by Spuxy** [Jelmerro/Vieb#331]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [ ] I have read the Erwic mode but i didnt get straight answer
- [x] I have read the info about flag --data-folder (i ran successfully new window)

**What needs to be solved**
Run new instance/window on my OS

I have downloaded by AUR. 
Distro: Arch

My cfg:
`" Options
set adblocker=update
set devtoolsposition=split
set downloadmethod=confirm
set firefoxmode=always
set fontsize=16
set mintabwidth=250
set norestoretabs
set permissioncamera=ask
set permissioncertificateerror=ask
set permissiondisplaycapture=ask
set permissionmediadevices=allow
set permissionmicrophone=ask
set permissionpersistentstorage=allow
set redirecttohttp
set splitbelow
set tabclosefocusright
set tabreopenposition=previous
set windowtitle=title

" Mappings
nmap <F3> <toSearchMode><nextSearchMatch>
nmap <S-F3> <toSearchMode><previousSearchMatch>
nmap <C-g> <toSearchMode><nextSearchMatch>
nmap <C-G> <toSearchMode><previousSearchMatch>
map <C-f> <toSearchMode>
map <C-h> <:history>
map <C-j> <:downloads>
map <C-k> <toExploreMode>
map <C-l> <toExploreMode>
map <C-q> <:quit>
map <C-s> <:write>
map <C-t> <openNewTab><toExploreMode>
map <C-I> <:devtools>
map <C-T> <reopenTab>
map <C-Y> <:downloads>
map <A-Left> <backInHistory>
map <A-Right> <forwardInHistory>
map <A-0> <:b -1>
map <A-1> <:b 0>
map <A-2> <:b 1>
map <A-3> <:b 2>
map <A-4> <:b 3>
map <A-5> <:b 4>
map <A-6> <:b 5>
map <A-7> <:b 6>
map <A-8> <:b 7>
map <A-9> <:b 8>

map <A-Left> <previousTab>
map <A-Right> <nextTab>
map <A-w> <:close>
map <A-S-Left> <moveTabBackward>
map <A-S-Right> <moveTabForward>

map <C-S> <:screenshot>
vmap <C-f> <p.searchText>
smap <F3> <nextSearchMatch>
smap <C-g> <nextSearchMatch>
smap <S-F3> <previousSearchMatch>
smap <C-G> <previousSearchMatch>

" vim: ft=vim
`
+ How should i map for <C+p> find thru files <:b ???> just trigger to see dropmenu

**Comment by Jelmerro** [comment]
I don't really understand your first question, with regards to the multiple instances. It says you found the data folder argument, but the title of the issue says "more instances than one?" which is exactly what the data folder argument is for. If you are looking for multiple windows in the same instance, there is already a bug for that: #141.

Erwic is an additional piece of startup config for starting a specific set of tabs on startup in specific containers, each time that the "erwic" instance is started. It can also be used with a custom app title and icon, to make it look like a different app such as Slack or Discord etc, all info should be in [Erwic.md](https://github.com/Jelmerro/Vieb/blob/master/Erwic.md).

For the final mapping question, the `<:b something>` syntax will always execute the command right away, so it can't be used for opening command mode and staying there, as it actually completely bypasses command mode if you use that syntax. What you want to do can be achieved with `nmap <C-p> :b<Space>`, or if you have changed the mapping for opening command mode: `nmap <C-p> <toCommandMode>b<Space>`.

Let me know if any of your questions are still unanswered, I'll close the issue for now as the questions seem answered, and no new features need to be developed, because all of it is possible already :slightly_smiling_face:
