### ISSUE TITLE
Place the cursor at the end of an input box

### ISSUE THREAD

**Issue by N-R-K** [Jelmerro/Vieb#341]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
When inserting onto an input box (eg. search bar) the cursor is placed at the beginning of the input box even when there's pre-existing text there.

For example when inserting on the github search box the cursor is inserted at the start of "is:issue is:open " instead of at the end which makes for a bad experience.

**Expected behavior**
The cursor should be placed at the end of an input box.

**Comment by Jelmerro** [comment]
I guess this makes sense, but the case where it remembers where you last had the focus still needs to be possible. Currently it just uses the default focus point, and from there remembers the cursor position, so we need a system to detect first focus and then set the cursor to the end, and use the default remember system otherwise. I'm not sure when I'll find the time to work on this myself, but to others who maybe want to contribute a PR I just wanted to have mentioned the above in advance.

**Comment by Jelmerro** [comment]
I have just added "inputfocusalignment" as a setting to control where the cursor should appear inside input fields, either at the start or end, also with the option to remember the position or set it each time. Previous (implied) default was "rememberstart", but I have now set it to "rememberend" by default, so it will start at the end, then remember the position until you reload or move to other pages.
