### ISSUE TITLE
Control url encoding/decoding for link copy and external applications

### ISSUE THREAD

**Issue by veikolippand** [Jelmerro/Vieb#365]
Is it possible to get current url as not url encoded with openLinkExternal?
Maybe there is way to solve this already but i might be blind and i don't see it.
I try to open PDF with script. I pass url with openLinkExternal to simple script where wget downloads it to /tmp dir and then file will be opened from that dir. All good until there is no special characters in file name which will be url encoded and confuses everything.
"_https://blah/blah/some_file(c).pdf_" will be "_https://blah/blah/some_file%28c%29.pdf_".
And i would like to avoid extra steps in my script to keep it small and simple.

**Comment by Jelmerro** [comment]
Not yet, let's add it as a separate action!

**Comment by Jelmerro** [comment]
On closer inspection, it would seem that pretty much all "link-related" actions (see `:h link-related) would need a decoded counterpart to the regular version, and maybe even a version that properly encodes them at all times. Currently it just returns them as is, even though it's fairly trivial to convert them, and they are already being converted in Vieb for various different purposes. Therefor I don't think a separate action for this makes sense (especially not if we want this to be consistent with other link-related actions), but instead a setting to control how links are presented to external applications would be nice (either "as-is", "encoded" or "decoded").

Internally the urls are all encoded and decoded as needed, so the newtab, split actions and such don't need such a setting, but it might be nice to add one for the copying of links as well. Given how there are also a lot of copy link actions already, it makes sense to make this a setting as well (either "as-is", "encoded" or "decoded"), instead of creating a separate action for each encoding type.

**Comment by Jelmerro** [comment]
I made all link copy actions and such pass by a new setting named `encodeurlcopy` and all external open actions by `encodeurlext`. You can use these to control the encoding as requested, go check out [the new 8.0.0 release](https://github.com/Jelmerro/Vieb/releases/tag/8.0.0)!
