### ISSUE TITLE
how to use <action.openLinkExternal> with follow mode?

### ISSUE THREAD

**Issue by vaderbugado** [Jelmerro/Vieb#367]
I want to make a key bind to start follow mode and open the link I followed with mpv.

**Comment by Jelmerro** [comment]
If you enter follow mode AFTER entering pointer mode, you can use follow mode to move the pointer, and then use the mapping `xl` or `xx` to open the hovered link externally. You can also do `xv` to open the hovered video link externally. The reason for this requiring pointer mode, is because otherwise you would need a follow mode for every single type of element which might have a source you want to open externally (audio, video, image or frame). If you just want to open the current page url externally, just `x` from normal mode will do, so you can also navigate to a video (or other source/page) and then press `x`.
