### ISSUE TITLE
[Fix proposal] Include Electron version in the user agent. Passes google's security checks (enables login)

### ISSUE THREAD

**Issue by nitanmarcel** [Jelmerro/Vieb#390]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
I'm not used to developing with electron and my nodejs experience is lacking so the best thing I can do is to open an issue.

The google login issue was coming from the Vieb all along and not because of the google's security checks. Please change to a valid useragent that also includes the Electron version similar to the Chromium (Chrome) version.

A working useragent for the current version of electron (19.0.6) would be 

`Mozilla/5.0 (Window NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Electron/19.0.6 Chrome/102.0.0.0 Safari/537.36`

And not 

`Mozilla/5.0 (Window NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

Google login gets fixed after that

![image](https://user-images.githubusercontent.com/41646249/176644579-f812c90c-3188-4d9f-8485-7060a2823354.png)

**To Reproduce**
Use the default useragent set my the app at the moment and try to open google's login page. Insert your username/email then press next.

Now use the useragent from above that contains the electron version.

**Expected behavior**
The default useragent will fail. The mentioned one with the electron version will succeed.

**Specs**
 - OS: Windows 11
 - Version: [8.1.0

**Comment by Jelmerro** [comment]
I apologize in advance for potentially being rude, but here goes nothing:

This entire post seems to be based on the assumption that if Google accepts a useragent it is somehow better. This is false and hurts the web as we know it. Google is doing this to make you expose this info to them, and as a result allow you to login, as many people using Google from within Electron have complained that they weren't allowed to. Exposing the Electron useragent to websites is dangerous as it undeniably confirms that the browser is Electron-based. I will NOT add this to the useragent, even if Google allows you to login with it. The current useragents are NOT broken, and are exactly the same as the default in Chromium/Chrome/Firefox and should remain as such. If you consider exposing a different useragent a worthy trade-off to be allowed a login to Google services, that's your decision, but shouldn't affect every single Vieb user by default. I will consider adding it to the FAQ item on Google logins, but I will never ever change the default useragent to something non-standard because Google wants us to. I would rather make a browser that doesn't by default allow you to use broken services than to add workarounds imposed by these kind of companies, I thought the FAQ was very clear about this.

I hope this made the situation clear, thanks for understanding.
