### ISSUE TITLE
Mapping actions to a key will render that key unusable in text boxes or commands

### ISSUE THREAD

**Issue by nitanmarcel** [Jelmerro/Vieb#409]
**Checklist**
- [X] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
I wanted to try actions by mapping the markdown viewer to the key `p` and since then I cannot use the respective key neither in input or command mode making it impossible to unmap it.

**To Reproduce**
- Create a new map for an action on any key
- Try to use the key in input mode or try to unmap it from the command mode.

**Expected behavior**
Should probably not trigger if input or command mode is enabled? At least in command mode since you need to press the key with the `unmap` command to remove the map/

**Specs**
 - OS: Linux
 - Version: 9.0.0

**Comment by Jelmerro** [comment]
This is intended, as with `:map` you can create mappings for every mode. If you do not want this mapping outside of normal mode, you can use `:nmap` and `:nunmap` instead of regular `:map` and `:unmap`. The same is true for any mode, they all have a specific map command to map only for a specific mode. Executing `:map p "something"` with "something" being your mapping, will ALSO make `p` do your "something" inside search, command and explore mode. Let me know if you need help with making a specific map command or if you have any other questions.
