### ISSUE TITLE
Implement Brave Browser AdBlock

### ISSUE THREAD

**Issue by kjlo** [Jelmerro/Vieb#418]
**Checklist**
- [x] I've searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
I've been using Vieb for some months and I like it because it feels like Neovim but I noted a consistent problem with the AdBlock on some sites especially Youtube (I know that this is a problem reported before). At the same time, I've been using [Brave](https://github.com/brave/brave-browser) with [Vimium C](https://github.com/gdh1995/vimium-c) and the AdBlock is excellent in every aspect but the experience with a Vim-like browser is limited.

**Alternatives considered**
Brave has a [library](https://github.com/brave/adblock-rust) for their own AdBlock that could be implemented through Node.js (and Rust) but they warn of a loss in performance. I don't have experience with Electron but I'm interested in knowing what you think about it.

**Comment by Jelmerro** [comment]
I am not against this idea, but I have tried this in the past and it did not work. I want to note the following things in case they are useful for other people to implement this:

- It's a native module, this means you have to compile the module before being able to build and electron package, this has varies quirks, but usually means that you need to have more native dependencies installed.
- There is virtually no documentation how to implement this, besides a single code example. I couldn't get it to work based on just that.

I will check again briefly if things have changed since last time, but otherwise I'll add the `help wanted` label. I'll get back to you once I have found the time for this.

**Comment by Jelmerro** [comment]
Sadly, the requirement for install cargo/rust globally to even install the module has not changed. I also do not see any options to do cosmetic filtering. I do not see this module being suited for Vieb anytime soon, and will therefor close this issue. I would welcome PRs for it if they do not need a global rust install and do cosmetic filtering, both of which seem highly unlikely at this point though.
