### ISSUE TITLE
Support for multiple windows is necessary.

### ISSUE THREAD

**Issue by I03D** [Jelmerro/Vieb#430]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ ] :) I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues) - https://github.com/Jelmerro/Vieb/issues/141

**Addition or change**
I need to open multiple browser windows in i3 (it's perfect for working with multiple windows). If it becomes easy to do, I will finally be able to replace Chrome and Firefox.
![2022-10-22_17-24](https://user-images.githubusercontent.com/98839825/197336617-3c6c32ed-c67b-4817-a4a5-eaa0dbe4444e.png)

**Alternatives considered**
I can't always use splits as an alternative to windows, because they can't be in different workspaces. Also, third-party windows cannot be placed between splits.
I didn't quite understand your advice in https://github.com/Jelmerro/Vieb/issues/141 . If the Vieb can be run in different folders, then it's either difficult to automate using console commands, or it's not what I need at all.

**Comment by Jelmerro** [comment]
This is actually a chromium/electron issue, in 141 I tried to list the alternatives to using multiple windows in the same folder, but it's not a use case that is actually supported at all, due to the nature of cookies and localstorage. While chromium has a bunch of workarounds in place to allow you to use multiple windows, electron and by extension Vieb do not have an option for multiple windows, that is if you care about keeping your data. You could modify Vieb to start with multiple windows, but this WILL result in corrupt cache, localstorage and cookies, and thus wipe your data for every additional window. I will close this in favor of 141, where the progress of is this issue will be tracked, but I will answer questions below if you still have them. But in short, multiple windows in electron is not supported and thus Vieb doesn't have it either sadly.
