### ISSUE TITLE
Point Vieb to utilize another shell?

### ISSUE THREAD

**Issue by kbwhodat** [Jelmerro/Vieb#446]
Sorry for this dumb question I really tried to figure it out.

I see when an external command gets executed it uses /bin/sh. Could this be modified to bash or zsh?

Reason being, I have aliases that I would like Vieb to use but it does not seem to have knowledge of them due to the fact it utilizes a different shell.

Any feedback would be helpful, thanks in advance.

**Comment by Jelmerro** [comment]
Vieb itself does not choose a shell, neither does Electron, it seems like node uses sh by default for exec: https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback
Though there is an option to change it. This is not implemented in Vieb yet, but I will make a new setting in the future to do so. In the meantime, you can try this:
https://stackoverflow.com/q/62140800

**Comment by kbwhodat** [comment]
I'm using macos. For anyone facing this issue where sh is being used by default and not recognizing some your binaries make sure to specify the full path to the binary; even common ones like sed, cut etc. 
eg. `/usr/bin/cut` instead of `cut`

@Jelmerro I see you added changes to make shell dynamic now! Very cool! I tested it out and it looks good. I wouldn't have to do what I mentioned above. Good stuff!

**Comment by Jelmerro** [comment]
Glad that it works now, I decided to also use the `$SHELL` variable, unlike what node does by default, as that seems like a nice way to not have to have this setting always configured with custom shells.

As for the next release, it depends. I hope to make one in the next week, but definitely before the end of the month as the new Electron stable will be ready at the end of the moment. I'm currently testing the beta version for stability, but a lot has been improved since the last release, so I might just make a new Vieb build soon.
