### ISSUE TITLE
switch darkreadermode

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#451]
nmap <C-.> <:set darkreadermode=light><refreshTab>
nmap <C-,> <:set darkreadermode=dark><refreshTab>

dark to light works 
light back to dark takes several times till it switches.
test site was google.com

Is my approach faulty?

**Comment by Jelmerro** [comment]
It seems to work here, did you try the commands separately without the mapping? And does it also break on other sites when switching?

**Comment by se7en-x230** [comment]
manual or automated make no different.

nmap <C-.> <:set darkreadermode=light><refreshTab>
nmap <C-,> <:set darkreadermode=dark><refreshTab>

Other sites like bing.com not change at all.

set darkreader=true
set darkreaderblocklist="^(?!.*github.*)"
set darkreadergrayscale=100
set nativetheme=dark

**Comment by Jelmerro** [comment]
If you do `:set nativethem=light` when switching to the light theme, does that help, or not at all?

**Comment by se7en-x230** [comment]
I moved .config/Vieb out of the way to start with all defaults.
Only setting in my viebrc is 
set darkreader=true

I can switch manual :set darkreadermode=dark/light and automatically as long as I do NOT enable
darkreaderblocklist 
once that is anabled I am not able to use the set command or the keybindings.

Only trouble I have is that switching back to light will keep some fields dark.

![image](https://user-images.githubusercontent.com/69777713/202881225-70789ff9-b332-43de-a5ff-b7328d8b3887.png)

**Comment by Jelmerro** [comment]
This is because you have added a inverted pattern to the blocklists, meaning it will be used as an allowlist. You can do `:set darkreaderblocklist=github.com` not the inverted pattern, as this will match everything EXCEPT github, meaning it will block everything from using darkreader besides github. This is working as intended, please let me know if you have other questions, I should probably make this more clear in the help.

**Comment by se7en-x230** [comment]
Oh wow ... do I feel stupid now :)

Okey but I still have one question. 
Why does :set darkreadermode=light not return to the original page design (see google.com screenshot) but keeps see upper part dark?

**Comment by se7en-x230** [comment]
Wouldn't it be easier to have 

nmap <C-.> <:set darkreader=false>
nmap <C-,> <:set darkreader=true>

to switch darkreader all together  on and off?

**Comment by Jelmerro** [comment]
The light theme of darkreader isn't perfect sadly, but this is not a Vieb issue. It's more of a dimmed theme, and they mentioned that a perfect light theme is not the focus of the project. Since many pages default to white, it would indeed be an option to toggle darkreader completely instead of toggling the light/dark version.
