### ISSUE TITLE
Cannot open Vieb on Mac M1

### ISSUE THREAD

**Issue by retrotechie** [Jelmerro/Vieb#464]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I found a similar issue in the [issue tracker](https://github.com/Jelmerro/Vieb/issues) and ran `sudo codesign --force --deep --sign - /Applications/Vieb.app` but did not work
  - #169

**Describe the bug**
![Screenshot 2023-01-26 at 10 41 45 PM](https://user-images.githubusercontent.com/107520616/215026856-e976df90-54f7-45f4-8ead-6785c7d27ee3.png)

Cannot open Vieb on Mac M1

**Specs**
 - OS: macOS 13.1 arm64
 - Version: Vieb 9.5.1

**Comment by Jelmerro** [comment]
Please see the [FAQ](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#mac). Mac requires signing, which can only be done on a mac, hence users need to do it themselves, as mentioned on the website and in the FAQ.

**Comment by j-hui** [comment]
@Jelmerro I encountered this issue too, and signing the signing the application doesn't work:

```
$ sudo codesign --force --deep --sign - /Applications/Vieb.app
Password:
/Applications/Vieb.app: replacing existing signature
$ vieb # shows prompt saying Vieb is damaged
zsh: killed     vieb
```

This happens for both the Apple Silicon app downloaded directly from the vieb.dev website and using Homebrew.

However, the `codesign` instructions _does_ work for the x86_64 app, downloaded from vieb.dev (I haven't verified this for the x86_64 app downloaded with Homebrew). In fact, the error message for x86_64 actually complains about unverified rather than damaged:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/11800204/219876779-9724f8d1-f125-4663-a6b8-ae80abe1e05d.png">

After signing it, and then going to System Preferences > Security and Privacy > Security to manually allow running this app, I was able to run the x86_64 version.
