### ISSUE TITLE
Is normal mode blocking the functioning of some web elements?

### ISSUE THREAD

**Issue by Fuann-Kinoko** [Jelmerro/Vieb#476]
I'm not sure if this is a feature or a bug.

When in normal mode, buttons that copy text when pressed don't work properly on websites, even if `permissionclipboardwrite` or something like that is set to allow. but as soon as you enter insert mode, these work fine.

Example:
- github's copy raw file button

Another example, which I'm not sure why, is that the search bar in the top right corner of the web discord, which does not expand or get focus in normal mode, no matter how many times you click it, but it works fine once you enter insert mode.

**Comment by Jelmerro** [comment]
Yes, sadly some of these APIs require window focus in Chromium for security reasons, as otherwise they are blocked. Copying to clipboard is one of these APIs, and as such either requires you to either use follow mode to click on it (which correctly sets focus), use pointer mode to click on it (which correctly sets focus) or go into insert mode before using the mouse to click on it.

I should probably add this to the FAQ, but in all fairness it's mostly bad feedback by websites saying that the copy action succeeded even though it clearly gave an error...

**Comment by Fuann-Kinoko** [comment]
Thank you for your reply, since this is an unsolvable problem, I think this issue can be closed

**Comment by Jelmerro** [comment]
I made a note of it in the `permissionclipboardwrite` setting, will be included in the docs for the next release.
