### ISSUE TITLE
Page loading indication

### ISSUE THREAD

**Issue by dinkocar** [Jelmerro/Vieb#477]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
I have navbar always showing and tabbar shows on change.
When tabbar is hidden there is no indication if page is loading, or it is finished loading or what. It would be good to have some indication if page is still loading, like blue line on top of the page (inspired by github :) ).

**Alternatives considered**
None

**Comment by Jelmerro** [comment]
It's sadly not possible to get a percentage, an approximate duration nor any kind of progress on the loading of the page. It starts loading and eventually it stops. So while I would appreciate a custom loading bar, in terms of progress we can't do much more than a spinner. Github can do this themselves because they know what they will load, and made estimates for how long each component takes to load, and even then the movement of the loading bar is pretty shaky and inconsistent.

While I'm open to implementing different types of loading indicators, I can't think of other decent locations for it besides in the tabbar. Any suggestions are welcome, but keep in mind that progress indicators are not possible.

**Comment by dinkocar** [comment]
It could just be blue (customizable or not)  line with animated gradient, just to give information to the user that something is going on in the background.

**Comment by Jelmerro** [comment]
Implemented in 11.0.0 :tada:
