### ISSUE TITLE
Navbar / Tabbar position

### ISSUE THREAD

**Issue by dinkocar** [Jelmerro/Vieb#478]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer asking my question on Github instead of [r/vieb](https://www.reddit.com/r/vieb/), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**What needs to be solved**
How to I place navbar on bottom? I saw screenshot with such look, but I can not find any settings related to it.

**Steps that have been attempted**
[TODO A list of things you tried to use the feature or solve a problem, and what doesn't work when you use them.]

**Comment by dark-steveneq** [comment]
There's no way to change positions of the UI elements of Vieb... kinda. Actually, there is one. By using :colorscheme​ command, you can switch the "internal" CSS style. By default, there are : default​, flipped​ (the one you're interested in)​, verticaltabs, light​, compact​ and much more. You can use your own CSS styles by putting them in Vieb/colors​ folder.
------- Original Message -------

**Comment by Jelmerro** [comment]
This can indeed be done with colorschemes as mentioned above. The colorscheme you are looking for is called `flipped` and can be activated with `:colorscheme flipped` either in command mode or in your viebrc file. The arrow keys work fine in this scheme, they just get inverted with the theme because the bar is at the bottom instead of the top. If you don't want this, you are free to make a custom theme that keeps the order of suggestions unflipped but only flips the other UI elements. You can copy over the flipped colorscheme from [here](https://github.com/Jelmerro/Vieb/blob/master/app/colors/flipped.css). On line 21 there is the following:

```css
#suggest-dropdown {top: auto;bottom: 2.1em;flex-direction: column-reverse;
```

As you can see it was a deliberate choice to revert the suggestions, as otherwise the first selected suggestion would be at the top, which also would be a bit inconsistent. I decided to flip everything to make it start with the nearest selection just like it would in the default theme. If you don't want this to be flipped unlike the other elements, just make a theme in any of the locations listed in `:help :colorscheme`, for example `~/.vieb/colors/custom-flipped.css`, and paste the contents of the [flipped theme](https://github.com/Jelmerro/Vieb/blob/master/app/colors/flipped.css), then change `column-reverse` to `column` on line 21 (the one listed above with `#suggest-dropdown` at the start).

I believe this should solve your problem, if not let me know or ask any remaining questions you might have.
