### ISSUE TITLE
Can't delete selected mails on GMail

### ISSUE THREAD

**Issue by yi-yunseok** [Jelmerro/Vieb#485]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**

Vieb don't respond when I trying to delete selected mails.

**To Reproduce**

In the GMail, select multiple mails and then click Delete.

**Expected behavior**

Mails must be moved to the Trash.

**Specs**
 - OS: RasPiOS arm64
 - Version: 6.1.32x

**Comment by Jelmerro** [comment]
I suppose you are trying to use the mouse for that? Could you give more details of what steps you are using to delete them? Could you confirm it does work when using follow mode? And also what happens when using the pointer to left click on it, or if you use the pointer's `insertAtPosition`, see `:help p.insertAtPosition`.

**Comment by yi-yunseok** [comment]
Thank you. It working well with `Insert` mode, rather than `Follow`.
