### ISSUE TITLE
Google services do not allow Vieb to login

### ISSUE THREAD

**Issue by camflint** [Jelmerro/Vieb#50]
When I try to log in to any Google property, I get this error message:

![image](https://user-images.githubusercontent.com/2079548/83338319-293f2200-a278-11ea-82c4-5a73f0f69660.png)

Perhaps we need to report a different user agent.

**Comment by Jelmerro** [comment]
What part of the useragent seems non-standard to you if I may ask?
I don't understand why everyone assumes it's the useragent without checking that themselves. As far as I know there is no difference and there is no way to fix this in Vieb, please let google know that are having these silly issues.

Given the amount of people opening these issues duplicate issues I will leave this open for visibility.

**Comment by Jelmerro** [comment]
https://support.google.com/accounts/answer/7675428
Vieb is probably being flagged for one the bullet points listed (such as embedding in different applications), which is nothing that can be "solved" by Vieb. My only recommendation is to report this to google and let them get this fixed, because even people who are using the official google version of chrome appear to be having these issues every now and then:
https://support.google.com/chrome/thread/23340584

**Comment by Jelmerro** [comment]
Okay, as a further confirmation that this is out of Vieb's control, other Electron users and contributors also mention that there is nothing that can be done by Electron to solve this. You are basically at the mercy of google to allow the login, which they can block for any reason they deem acceptable:
https://github.com/electron/electron/issues/22346

**Comment by andys8** [comment]
Qutebrowser uses site specific workarounds/useragents

https://github.com/qutebrowser/qutebrowser/issues/5182

**Comment by josemiguelo** [comment]
For what it's worth: I had the same problem and even some sites using Cloudfare like Medium were banning my ip because of my User Agent. I solved the problem by doing: 1. hardcoding the user agent at https://github.com/Jelmerro/Vieb/blob/master/app/index.js#L176 (I used `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0`) and 2. build the app from scratch using `npm run build`. So, I think loging into any Google site is totally doable. I'm doing it right now. Maybe we can set a custom user agent by setting a variable in the rc file?

> When I try to log in to any Google property, I get this error message:
> 
> ![image](https://user-images.githubusercontent.com/2079548/83338319-293f2200-a278-11ea-82c4-5a73f0f69660.png)
> 
> Perhaps we need to report a different user agent.

**Comment by Jelmerro** [comment]
It is possible to change the useragent to use a workaround for these broken checks, but I definitely want this to be an optional setting. The problem with that is that a setting for custom useragents with the "set" command would be tedious and that Vieb does not have dictionaries or something similar to configure more complex settings like domain specific useragents.

What could work is a setting such as "firefoxuseragent", with options like: "always", "google" and "never", for which the default would obviously be set to "never". Because bending over with workarounds like this to please specific websites should always be optional.

The final remaining point is that there is a bit of difficulty in keeping the useragent up to date with new Firefox releases. Given the evergreen nature of Firefox and the time-bound releases a function could be written to predict the version. Worst case is that Vieb would need to fetch the latest useragent from some kind of external service (which isn't something that Vieb should connect to without user permission).

**Comment by andys8** [comment]
Again for reference what Qutebrowser is doing to workaround. 

https://github.com/qutebrowser/qutebrowser/blob/c04ab823a84b974fd26f5bbb1f9e6a6a175c038a/qutebrowser/browser/webengine/webenginesettings.py#L411

I'd even go as far as not having user settings for these specific sites and just change the user agent the same way. These quirks are nasty. But on the other hand a browser not supporting Google out of the box is an issue.

**Comment by Jelmerro** [comment]
It's a nasty policy and this is a hacky workaround, not something that will fix the problem. Maybe on the short-term, but absolutely not long-term. Users should decide for themselves if they want to commit to this, without abstracting it away as if this is fine. It's not, it's hurting the web as we know it, and people should think twice about accepting these kind of hurtful policies by companies. Besides, it's not like Google can't detect that you are doing this in the first place, if they wanted to they could easily detect if you are really using Chrome, Chromium or actually using Firefox (instead of merely changing the useragent). Having said that, I'm okay with a setting that will allow users to change it, but that will be at their own risk.

**Comment by Jelmerro** [comment]
I have recently added a `firefoxmode` option, which among other navigator changes also updates the useragent. One of the possible uses of this option is to attempt to trick Google to allow your login attempt. If you can't wait till the next release to login to your Google account with Vieb, you can build it from source and let me know if the `firefoxmode` works as expected. As said before, the mode is NOT enabled by default, but you can of course change the settings to your liking with `:set` or the viebrc file. Whenever the next Vieb release will happen, the `firefoxmode` will be one of the new features included. As a result of adding the only known workaround for Google's login policy, this issue will be closed. If you still experience problems with your Google account while using the `firefoxmode`, you will need to reach out to Google.

**Comment by zUnixorn** [comment]
For anyone not able to login to google even when using firefoxmode, for me going to https://myaccount.google.com/security (from a browser I was already logged into google) and turning on 'Less secure app access' enabled me to log me in to google. Afterwards I was able to turn it off again and stay logged in.

**Comment by Jelmerro** [comment]
I'll add it to the [FAQ section about google signin](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#why-cant-i-sign-in-to-google) in a bit, so people don't have to crawl through issues to find workarounds for Google's blocking policy.
