### ISSUE TITLE
[Enhancement] Rebase using Ungoogled-Chromium and Thorium's performance patches

### ISSUE THREAD

**Issue by xplshn** [Jelmerro/Vieb#509]
That's it, I thought it'd be great if Vieb were completely Ungoogled and had the Thorium browser performance patches(Thorium is based on Chromium) and Ungoogled Chromium is a drop in replacement for Chromium based projects.

**Comment by Jelmerro** [comment]
I like the idea, but a couple of things must be made clear here:
- First, Electron is not "just" a custom chromium build, it also has its own API that Vieb uses extensively to create its functionality. One of the big reasons for choosing Electron is because the build process for custom chromium is both time- and resource-intensive, while Electron can be used with static binaries that can then run NodeJS programs, like Vieb. Regardless of the duration of building, the usage of Electron's API means that whatever other Chromium build or tools are used as the basis, there will always need to be the additional step of building Electron based on that custom Chromium, hence a double build process that requires even more resources. At this point you would just have the additional work of building two entire projects from scratch, but this is not the biggest issue.
- Secondly, while Electron is very similar Chromium, it is not exactly the same. Electron itself has a lof of Chromium patches in place, that are not directly compatible with other Chromium forks or patch-sets. One would personally need to maintain a mixture/combination of both patch-sets (mind you there are [a lot](https://github.com/electron/electron/tree/main/patches/chromium) in Electron), I can see the same being true for either Thorium and/or Ungoogled. This creates another layer of work that I would actually think is bigger than creating the entirety of Vieb: it requires you to merge patch-sets for two very big projects into one set that works, then build it (which also takes hours), and only then can you hope to use just that one version of Chromium as the basis for building Electron (which also takes around an hour total) and only then could you even start using it. All this work does not mean that it is now over, all theses hundreds of patches as well as the source code for both projects are constantly in development, so all the changes from both projects and the patches from them would need to be kept up to date, probably a few times a days, since there are commits to Chromium pretty much every minute (not that every change means a conflict in the patches, but just to illustrate the problem that the amount of work grows exponentially).
This in combination with the enormous increase in difficulty to create your own custom Vieb build. This would mean no more AUR, Flatpak etc. basically all the custom builds, since they require the same build process from scratch, which now takes just a minute or two because Electron is pre-built, would then be hours to do for just a single platform.

I am however completely for the idea of allow users to do this if they do so desire. I am simply not going to do it personally, but you can already use Vieb with custom Electron builds if wanted. Just download/clone the repo, do an `npm ci` and you are ready to run Vieb. To then use a custom Electron to run Vieb, you can do `electron app` where `electron` can be whatever build of Electron you want. For example of FreeBSD, I have recently got Vieb running from source by install `electron25` from the ports repo and run the cloned Vieb with `electron25 app`. This did exactly what you expect: Run Vieb with a custom build of Electron. This is just to illustrate that this is already possible and supported, just not advertised nor included, as that would result in a lot of extra work as explained above. I hope you can agree with my reason for closing this out, do let me know if you have any further questions or suggestions :)
