### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by mentalisttraceur** [Jelmerro/Vieb#516]
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Addition or change**
If I can get Vieb to the point where it's my daily-driver browser, I'd really love an Android port.

Wouldn't need much by way of interface changes - just need a way to bring up the keyboard (in a raw mode rather than normal text input mode, like how Termux does, so that autocomplete/autocorrect/etc doesn't get confused... maybe also add a little customizable bar for modifier+special keys that most keyboards don't have, against Termux is a good example).

Two things I would **really** love to have on a mobile port (because it would allow me to use my hypothetical sync solution from #515):

1. a way to programmatically tell it to open/close tabs from other apps - I'm going to need to drive it with commands from Termux. I don't care if the control scheme is Android intents, a local socket, or whatever - anything.

2. a way to have the datafolder on the shared storage (which partially emulates limitations of the FAT filesystems even on devices where it's not an SD card).

Is there willingness? What's needed to make that happen? What kind of help would you like/need? etc.

**Alternatives considered**
This is rather open-ended and what alternatives are viable, if any, strongly depends on a person's reasons for considering Vieb ported to Android.

**Comment by Jelmerro** [comment]
I would love a mobile/android port, but sadly Electron does not support android, so this is very unlikely to happen without starting from scratch. Sorry :(

**Comment by Jelmerro** [comment]
Also, regarding your two things you would want to have before porting, the first regarding programmatically changing Vieb data, is planned in #192 and #155, while the second point is already there because you can change which `datafolder` Vieb uses with either `--datafolder` or `VIEB_DATAFOLDER`, see `vieb --help` and `:help datafolder`. How this would translate to android I have never needed to consider. An android port is so unlikely that it was dismissed from being taken into account at all for planning out Vieb's features and usage.
