### ISSUE TITLE
Support for NT 6.1

### ISSUE THREAD

**Issue by andika207** [Jelmerro/Vieb#539]
Does anyone know if there is an old release that still supports Win7 ?

I have zero interest on Win 11, 12 and such crap.

**Comment by Jelmerro** [comment]
As per https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
Any release (or custom build) that uses Electron 22 or older is supposed to work on Windows 7. This is in line with both Electron and Chromium, and as such is not something that is solvable in Vieb without using a very old/outdated version of Electron/Chromium. Feel free to fork the project and make it work again for the old Electron 22 version. You can find breaking changes of different Electron versions here: https://github.com/electron/electron/blob/main/docs/breaking-changes.md, which should help with bringing the version down to 22, as Vieb is currently using 28. I would recommend to do only 1 or a few versions at a time, so that it is not all at once. Good luck, and sorry for not being able to provide updated releases for old Windows versions, it's beyond my control sadly.

**Comment by andika207** [comment]
> Any release (or custom build) that uses Electron 22 or older is supposed to work on Windows 7.

https://github.com/weolar/xpchrome/releases

**Comment by Jelmerro** [comment]
This is only a custom chromium build, to make it work for Vieb you would need to find/create something similar for Electron. That does depend on Chromium, but it is not the same. So without a custom Electron build for xp/win7 etc. we are sadly as far from a working Vieb on those systems as we are now without downgrading Electron/Vieb. Good find though for those who are interested in this.
