### ISSUE TITLE
Command history like in vim

### ISSUE THREAD

**Issue by BoolmanO** [Jelmerro/Vieb#560]
**Checklist**
- [true] I searched the `:help` documentation using `/` for helpful information
- [yes] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [definitely] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [looks like yes] I prefer making an issue instead of using [discussions](https://github.com/Jelmerro/Vieb/discussions), [Matrix](https://matrix.to/#/#vieb:matrix.org) or [Telegram](https://t.me/vieb_general)

**Addition or change**
I started using Vieb relatively recently, but I really like this browser and that's why I decided to open this issue. 
I suggest adding a history of commands, much like in Vim and Bash: up arrow - previous command in the list down arrow - next command. I really miss this functionality, I hope you have enough time to implement it :)

**Comment by Jelmerro** [comment]
Did you try `<c-p>` and `<c-n>`? These are mapped to `commandHistoryPrevious` and `commandHistoryNext` in command mode, and to `exploreHistoryPrevious` and `exploreHistoryNext` in explore mode. You can find help for command and epxlore mode at `:h command` and `:h explore`, both of which explain this basic functionality. If you want to jump to the action's help directly, you can do `:h commandHistoryPrevious` for example. The reason for not using the arrow keys is because those are used for suggestions already. If you meant a different kind of history, please let me know.

**Comment by BoolmanO** [comment]
Thank you very much for your answer, this is exactly what I need. Then, so that this issue is not completely useless, I suggest adding a mention of hotkeys for the actions (I actually found this topic in the help page, but there are no default hotkeys there)

**Comment by BoolmanO** [comment]
Thank you very much for your answer, this is exactly what I need. 
Sorry ^)

**Comment by Jelmerro** [comment]
You're welcome, keep in mind you can always change the mappings if this is different than what you want using familiar `:map` commands.
