### ISSUE TITLE
Mouse clicks outside of insert mode can't open menus on some websites

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#62]
When trying to adjust the youtube playback speed, I click the right bottom icon and it pops up a menu for further choices. But when I click on the speed section in the menu, the click pass through and pause the video. Not sure why that happened.

**Comment by Jelmerro** [comment]
Is this a one time thing, or can you reproduce it? And in what mode were you when this happened?

**Comment by ipod825** [comment]
It always happen. In Normal mode.

**Comment by ipod825** [comment]
No it's not happening in Insert mode. Is it fixable?

**Comment by Jelmerro** [comment]
The problem is that the website requires the mouse the remain focused on the page at all times, or it will close menus like this, because it "thinks" that you don't want the menu anymore. The problem with mouse focus is that it also means keyboard focus, which is in direct conflict with what Vieb is trying to do. Insert mode is specifically there to move all of the focus to the website, so you still have the option to use the site normally. As far as I'm concerned these type of menus are poor website design. There is nothing that Vieb can do to solve this without permanently moving the focus to the website, which would result in issues like #51 and a huge amount of further complications.
