### ISSUE TITLE
Rethink about insert/normal mode

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#63]
This is related to #62 #56 #57. 

The behavior of normal mode and insert mode of Vieb is quite different from other vim-inspired browser.

__Normal Mode__
In other vim-inspired browsers, keys are not all grabbed. Rather, I think they only handle mapped keys. If a key is not mapped, it is passed through to the website. So in site like youtube, `<Left>`, `<Right>`, if not remapped, they are passed through and fast-forward/backward the playback.

On the other hand, in Vieb normal mode, all keys are grabbed by Vieb, and unmapped keys are not pass-through. Which make `<Left>`, `<Right>` does nothing in yotube. This can be solved if per-site pass through is implemented. However, I think a more user-friendly way is to just pass-through unmapped keys.

__Insert Mode__
Insert mode in Vieb is more like Normal mode in other vim-inspired browsers, which handle all mapped keys but pass through all unmapped keys to the website. However, when entering insert mode, a side effect is to enter the first input field in the page. So if I want to fast-forward/backward in youtube, I need:
1. Press `i` to enter insert mode.
2. Click the video component to focus at it

While in other vim-inspired browser, this can totally be done without any extra step in normal mode. 

The behavior of Vieb and the name `Insert mode`, IMHO, is counter-intuitive and cause extra burden for simple things. So I think it should be consider to redesign the behavior of these two modes. As a side note, other vim-inspired browser might also provide another mode named `pass through`, which passes all keys to the web page except for one single key to exit `pass through` mode.

**Comment by Jelmerro** [comment]
It is quite different and that is by design. One of the main reasons for starting Vieb has been the confusion that most extensions cause by not having a separate modes. For even the most basic actions such as scrolling a page with `j` and `k`, the page could sometimes do completely different things.

Switching between modes to do different things is part of the Vim experience, because it gives you the power to separate different functionality without resorting to obscure key combinations or the mouse. This is the same for Vieb's insert mode and normal mode. I will not reconsider this design choice of Vieb and I suggest to look elsewhere if the advantages do not outweigh the negatives for you regarding this mode separation.

The pass-through ticket will remain open, because I consider that to be the solution of this problem, rather than removing the separation of these modes entirely.
