### ISSUE TITLE
Add greasemonkey script support

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#64]
As title.This enables users to customize the behavior of the webpage, for e.g. add a panel in youtube to control the speed of the playback.

**Comment by Jelmerro** [comment]
I do think this could be added, seems like a nice way to allow users a bit more control over the pages they visit. I'm just wondering what makes "greasemonkey" scripts different from regular JavaScript files. I am familiar with the browser extension that runs those, but if there is no difference with regular JavaScript, it could be relatively easy to implement this actually without using the extension or anything greasemonkey related for that matter.

**Comment by ipod825** [comment]
I am not sure. But probably the header of the script specifies some metadata such as the url regex the script applies?

**Comment by Jelmerro** [comment]
It seems like there is indeed a metadata section, but also that there are some global variables that are used inside of the user scripts. More details can be found below, I'm going to read about it later.
https://wiki.greasespot.net/Greasemonkey_Manual:API

**Comment by Jelmerro** [comment]
So as the next release of Vieb is going to have experimental extension support, I'm wondering what would be the best approach to implement this. I have tested the greasemonkey extension, sadly it doesn't work yet. So we have two options:

- Make the extension work by implementing the right APIs
- Give Vieb a separate greasemonkey parser as proposed when initially making this issue

My preferred solution would be the first one, as it gives people the option to install their preferred extension to manage the scripts, instead of requiring Vieb's implementation. It also has the advantage of killing two birds with one stone, as implementing the APIs to make the greasemonkey extension work is going to help expand support for other extensions as well.

So my suggestion would be to those interested in having greasemonkey support in Vieb, to contribute to making more extensions work. Though I will be keeping this ticket open for visibility until it's possible to run greasemonkey scripts in Vieb: either via the greasemonkey extension or when someone contributes a Vieb specific implementation for parsing the scripts via PR.

**Comment by Jelmerro** [comment]
Implemented in https://github.com/Jelmerro/Vieb/commit/3020a9462c8165bd82322ed03ba970299a7a5f19, see `:h userscript` for help.
