### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by andys8** [Jelmerro/Vieb#66]
I noticed the startup of the application takes currently around 3-4 seconds. Configuration, cache and history are vanilla. How are chances to improve this and lower the startup time?  

I think because it's an electron app improving startup time might be difficult. It look like there is space for optimization though:

* https://www.electronjs.org/docs/tutorial/performance
* https://github.com/zertosh/v8-compile-cache

I observed this in comparison to the browser I'm currently using (qutebrowser) and although it might not be one of the top priorities it might be nice if startup time could be improved :)

**Comment by Jelmerro** [comment]
The startup time is similar here, but I consider that quite fast already compared to the 5-6 seconds Firefox and Chromium take to start here. Possibly because of that, I haven't really spend time on the startup performance so far. I have briefly checked the performance tutorial and the cache package, both of which could help reduce the startup time.

Slightly related to this, I am exploring the possibilities of using a tool like webpack to load a single script instead of the 10+ that Vieb has to load now. If I can manage to make that work, I'm sure that the startup time will improve as a result. In the meantime, anyone is welcome to improve the performance of Vieb via a PR.

**Comment by andys8** [comment]
For comparison. On my system `chromium` takes around 0.8s and `qutebrowser` 1.6s.

Your answer makes sense though.

**Comment by Jelmerro** [comment]
I kind of gave up on the idea of using webpack (at least for now), so if somebody can get it to work, feel free to open a PR.

I just want to mention that the startup time can be improved using the `suspendonrestore` option of Vieb. With this setting you can make sure that not all the tabs will get loaded on startup, but just the visible one. I'm sure that this will help a lot with the startup time, so let me know if this gets it down to acceptable levels for you (@andys8).

**Comment by Jelmerro** [comment]
Since Vieb is finally using webpack for the last few releases, I feel like this improved quite a bit. I'll close it since it doesn't seem like there is much more we can do to reduce the startup time even further. Let me know if it's now also acceptably fast for you.
