### ISSUE TITLE
Vieb cannot browse Swedish furniture

### ISSUE THREAD

**Issue by gebner** [Jelmerro/Vieb#80]
When I try to open `ikea.nl`, I get an `ERR_CONNECTION_TIMED_OUT` error.  Setting `firefoxmode=always` does not seem to help.  Weirdly enough, it works just fine when I open `http://ikea.nl` directly.

AFAICT, this is because Vieb defaults to `https`.  Visiting `https://ikea.nl` in firefox/chromium also gives a timeout.  But the other browsers expand `ikea.nl` to `http://ikea.nl`, which does not trigger the bug (at ikea).

Not sure if there is something that can/should be done about this in Vieb.

**Comment by Jelmerro** [comment]
I can confirm that this is due to `https://` being the default protocol. Ideally Ikea needs to fix this, but I'm open to other workarounds, do you have any in mind?

**Comment by gebner** [comment]
This probably belongs in the same list as "google doesn't let me log in".  I've now found the `redirects` option which can fix this as well:
```vim
set redirects+=^https://(ikea\.\w+/.*)~https://www.$1
```
There's apparently a lot of sites that break when defaulting to https; the https-everywhere project has a whole list of rewrite rules here (for over 23000 websites...): https://github.com/EFForg/https-everywhere/tree/master/src/chrome/content/rules

BTW, I have `redirecttohttp` set.  Should this option have an effect here?

**Comment by Jelmerro** [comment]
Glad that you found a solution.

The `redirecttohttp` setting could be improved to handle this use case as well. Currently it only detects websites that have some kind of response on https, but no secure connection, for which it will either show the warning page or redirect if the toggle is set. Ideally we should keep the user in control to visit http websites instead of https, although in the Ikea example a redirect to `https://www.` is also enough, which might actually work for other sites as well. Maybe I'll just add a small note to the unavailable error page to check if the site only supports http (or if you are using the right protocol).

Personally I think the odds of running into this are small enough to just make a redirect, as I can't recall a single time when I had this issue, but I might have had it without noticing. If you (or anyone else) thinks this needs to be improved in Vieb just make a PR.
