### ISSUE TITLE
Feature Request: Theming support

### ISSUE THREAD

**Issue by B4rc1** [Jelmerro/Vieb#90]
I would really like to switch to vieb from firefox + tridactyl,
the only thing missing is theming support like firefoxses userChrome.css.
I know this would be possible through forking the project and editing the css files, but I'd rather not maintain that for the rest of my life. Is there the possibility for a mechanism like a userChrome.css, which allows to inject custom css into the Vieb?

**Comment by Jelmerro** [comment]
I think it would be cool to have this, but ideally we should strive for a design that works great out of the box for most people. If there are things you don't like about it I would much rather have a setting for it. Custom themes should be used only for custom themes, not to work around missing features, visual annoyances or other things that deserve more attention and polishing within Vieb.

From a technical view, I think it's possible to add this. I propose a `user.css` at the root of the datafolder to add custom styling to Vieb, which will be applied at startup (and also when running the restart command).

Finally, I usually don't tag people, but I think it would be really valuable to have more people involved in this discussion, especially because @gebner has made a wide range of CSS changes both as PRs and in their own fork of Vieb. I think these should either be integrated in Vieb, or be available as a custom theme, without having to keep a fork up to date with styling patches (though feel free to do so, as long as you inform people of the changes made in some way, as required by the [GPL3 license](https://github.com/Jelmerro/Vieb/blob/master/LICENSE)).

**Comment by B4rc1** [comment]
I totally agree, everything should *just work* and there should be no requirement for a `user.css`.

Additionally there should also be a way to access the "browser internal" devtools, attached to the webview of the main UI (tabbar, navbar, ...) for theming experimentation and debugging purposes.

**Comment by Jelmerro** [comment]
That's already there, use `--debug` as a startup argument. Do you have any example of things you would want to change with a `user.css` file?

**Comment by B4rc1** [comment]
a lot actually, i would try to replicate my firefox-look which has:
1. tab and url bar at the bottom
2. change colorscheme (of everything) to to my main colorscheme (inspired by [iceberg.vim](https://github.com/cocopon/iceberg.vim))
3. remove the logo
4. (maybe depending on looks) move/style the mode indicator

the most important for me is the coloscheme change, because right now on my linux machine it sticks out.

**Comment by Jelmerro** [comment]
Interesting to hear that a lot of people actually want to remove the logo (you are not the first to mention this), for me it's the only hint which instance of Vieb it actually is. I use around 3-4 separate instances, most of which are [Erwic instances](https://github.com/Jelmerro/Vieb/blob/master/Erwic.md), which use a different logo and name.

As for the colorscheme part of it, I think that you would also need to change the built-in pages, which will require more than 1 CSS file. So maybe we should use a directory for custom styling per page? So have `<datafolder>/styles/help.css`, `<datafolder>/styles/index.css` etc. What are your thoughts on this?

**Comment by B4rc1** [comment]
Your approach with separate folders also sounds interesting, but I would prefer, if everything had unique Id's/classes and only had to tweak one css file, which is included on every page so you don't have to include a `color.css` (with css variables for color-scheme) everywhere and not search/guess what file to write your css into.

Another approach without requiring to add ID's/classes to everything would be to create a `<datafolder>/theme/` folder and replicate the `Vieb/app/css/` structure and have for example a `download.css`, a `newtab.css` and so on, which are included on the relevant pages.

**Comment by Jelmerro** [comment]
The problem there, is that the help page or the download page don't run in the same context. They are just like any other page you visit. The pages you visit won't be styled with just a global `user.css`, but only the user interface such as the top bar, notifications and such. I can kind of see why you would want just a single CSS file, but with the special pages running similar to a regular webpage, you can't expect them to be affected by styling that is applied on the application layer.

We could do with just two files, one of the application layer and a separate one for the special pages, though there are probably pages that share ids and as such won't be individually customizable with such an approach. That's the reason why I suggested to introduce a separate file for each individual page and one for the Vieb application itself. Which is actually identical to how Vieb has separated the styling internally. I'll research a few other options, but it doesn't seem convenient to parse a single CSS and to split it up into parts before applying it, as that would basically be a more confusing implementation of just having multiple CSS files in a folder.

**Comment by B4rc1** [comment]
> They are just like any other page you visit. The pages you visit won't be styled with just a global user.css

I only have vanilla html/js/css experience and know hardly anything about electron, but cant you just include the `user.css` on these pages via
```<link rel="stylesheet" href="<datafolder>/user.css">```?

**Comment by gebner** [comment]
> I know this would be possible through forking the project and editing the css files, but I'd rather not maintain that for the rest of my life.

I wouldn't reject the possibility of forking vieb straight away. It is surprisingly easy to run your own fork, there is no complicated build system or anything.  For styling purposes you might also want to edit the html files.  Personally, I don't think overriding CSS would be enough for me.

> Custom themes should be used only for custom themes, not to work around missing features, visual annoyances or other things that deserve more attention and polishing within Vieb. [...] I think these should either be integrated in Vieb [...]

I completely agree, and I am busy submitting PRs for these changes once I've polished them a bit.

> Additionally there should also be a way to access the "browser internal" devtools

As Jelmer has already said, there's the `--debug` flag.  But this requires restarting vieb, which is cumbersome.  (And the devtools capture keyboard input, so you don't want to have it open all the time either.) Therefore I'd like an `:internaldevtools` command too.

**Comment by gebner** [comment]
Regarding the color changes: I want a light mode (and being able to toggle it manually when it gets dark).

Implementation-wise, one option could be to use CSS variables:
```css
:root {
  --fg: #eee;
  --bg: #333;
}

body {color: var(--fg);background:var(--bg);/*...*/}
```
The part defining the variables could be in a separate theme CSS file that is included by all vieb pages.

**Comment by gebner** [comment]
> Interesting to hear that a lot of people actually want to remove the logo (you are not the first to mention this)

Indeed, I have also removed the logo.  (I haven't used the erwic instances yet, so maybe that plays into it.)  Styling-wise, I found it too large and eye-catching.  Maybe it would be better if it was only as high as the url bar.

Some other "styling" changes I have in my fork:
 - Replaced the animated spinner by a still image. (I find animations to be distracting.)
 - I have changed the UI font.
 - The mode indicator is lowercase, and slightly smaller.
 - The background of the page container is white (instead of black) so that I don't get black flashes when navigating from one page to another.
 - I've enabled text selection using the mouse everywhere (does not yet work as well as I'd like).

This is how the top-left corner looks in my fork: 
![vieb-mode-status](https://user-images.githubusercontent.com/313929/99154680-ed770800-26b1-11eb-8001-c0a569d7c00c.png)

Changes I still want to do:
 - Light theme (as already mentioned)
 - Change the background color of the url bar depending on the current mode.
 - When you hover over a link, the url is displayed on the bottom.  I want this to be non-transparent, at most one line height, and aligned left (instead of center).

**Comment by Jelmerro** [comment]
@B4rc1 that could actually work, but I'm wondering if that would lead to a lot of duplicate id's across pages. I'll check tomorrow and let you know if that seems viable. Would be nice if we could keep it in one file without creating a lot of confusion.

Below I'll just quickly respond to the suggestions from @gebner, I think some of them have a place within the current Vieb settings:
- `CSS color variables`
I think this would increase the portability of Vieb's CSS and user themes, so I'll work on a separate color file in the future. This would also make custom themes a lot more easy to do, as one could just replace the colorscheme by changing the variables.
- `Replaced the animated spinner by a still image. (I find animations to be distracting.)`
Definitely could be a setting, didn't know this would be distracting to users, as most other browser have this, but I don't mind a setting for this kind of stuff as long as the default isn't changed.
- `I have changed the UI font.`
Would be cool if it could be a setting, but it might need additional config for fonts that are not installed.
- `The mode indicator is lowercase, and slightly smaller.`
I personally don't see why this matters much, but this could actually be done with the proposed `user.css`, as there is a [CSS rule for capitalization](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform).
- `The background of the page container is white (instead of black) so that I don't get black flashes when navigating from one page to another.`
I mostly use sites that have a dark theme, and all built-in pages are also dark, so I though it would be nice that the background of the loading page is also dark. However, if it flashes dark while loading a bright page, that is problematic, and should be fixable with the new themes. Have you tried the `darkreader` setting as well? Or do you simply prefer to view sites in a light theme?
- `I've enabled text selection using the mouse everywhere (does not yet work as well as I'd like).`
I don't use the mouse within Vieb, so I'm not sure how big this effort is, but feel free to improve mouse support for when the 'mouse' setting is enabled.
- `Light theme (as already mentioned)`
Should be possible when this issue is solved.
- `Change the background color of the url bar depending on the current mode.`
This is actually a great use case of custom themes, hiding the current mode is possible with that, and also setting the background color based on mode should be possible.
- `When you hover over a link, the url is displayed on the bottom. I want this to be non-transparent, at most one line height, and aligned left (instead of center).`
Another good use case of custom themes.
- `Hiding the logo`
As said, I would personally be very much against this, as it's an important indicator to show the user which instance of Vieb/Erwic they are using, but reducing the size might be a great compromise. Just make a new issue/PR and we can discuss the required changes, so that it can remain visible at all times without being an annoyance. Though if you want it gone, I would say that is also a use case of custom themes as well, and shouldn't require maintaining a fork just for that.

Hopefully that provides a bit of insight about my opinion of these changes. It's very good to hear that you plan to make a PR for most of these changes, and I welcome everyone else to do so if they think Vieb can do better.

**Comment by gebner** [comment]
Thanks for the comments.

> * `The mode indicator is lowercase, and slightly smaller.`
>   I personally don't see why this matters much, but this could actually be done with the proposed `user.css`, as there is a [CSS rule for capitalization](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform).

Indeed, I've just removed the `text-transform: capitalize` :smile: 

> * `The background of the page container is white (instead of black) so that I don't get black flashes when navigating from one page to another.`
>   I mostly use sites that have a dark theme, and all built-in pages are also dark, so I though it would be nice that the background of the loading page is also dark. However, if it flashes dark while loading a bright page, that is problematic, and should be fixable with the new themes. Have you tried the `darkreader` setting as well? Or do you simply prefer to view sites in a light theme?

Yes, I prefer a light theme, at least during the day.  It would sometimes be nice to `set dark` when it's dark, though.  I have tried the `darkreader` setting, but it feels a bit unreliable.  The first time I tried it, the github theming was broken.

I am aware of the flash problem.  You get it when you visit white pages with a black background, and also on black pages with a white background.  I'm not sure there's a better solution except to make it configurable.

> Hopefully that provides a bit of insight about my opinion of these changes. It's very good to hear that you plan to make a PR for most of these changes, and I welcome everyone else to do so if they think Vieb can do better.

BTW, I have a pretty long todo list.  Is it ok if I convert it into issues here?

**Comment by Jelmerro** [comment]
`Is it ok if I convert it into issues here?`
For sure, that gives people an indication of features/bugs to be worked on, while at the same time allowing an open discussion about the implementation.

With regards to the single file CSS themes, I think it would be possible, but it will require some work from my side. I'll experiment with alternative ways of loading the CSS so that we can reuse and customize it a bit better. Finally, I might rework the built-in styling to make use of color variables, that seems like a great addition in terms of readability.

**Comment by Jelmerro** [comment]
I pushed [a large commit](https://github.com/Jelmerro/Vieb/commit/4f34fc4b1cd6f943a041e0bc4b79618d8d601baf) that adds the "colorscheme" command with help documentation. I also reduced the logo size and made the navbar/tabar two distinct things in the code (so that they can be moved separately). Given that all pages and the app now use the same CSS that you can completely customize, it will allow you to make any kind of theme you can think of, including the relocation of elements. I already included a fresh new light theme and an experimental "flipped" theme to move the controls to the bottom. Let me know what everyone here thinks of the changes and especially if there is anything I missed.

**Comment by Jelmerro** [comment]
I have included this in the latest Vieb release and personally found no issues with it. If there are any, or you want to add something else as well, feel free to comment or open a new issue.

**Comment by gebner** [comment]
This is great!  All my styling changes now fit into the [color scheme css](https://gist.github.com/gebner/8a20c62725137cbc2e8ce24ecf3070cd).  I also like the new icon size.

Placing the configuration files into the data folder is a bit awkward though.  I now need to symlink the colors directory into every app folder manually.  This makes creating erwic instances a bit cumbersome.  How about (also) reading styles from `~/.vieb/colors`?  (Just like vieb reads both `~/.viebrc` and `$appData/viebrc`.  There might also be more folders in the future, e.g. for user scripts #64.)

**Comment by Jelmerro** [comment]
It seems like it's about time to make a user `~/.vieb/` folder for user specific config, but I didn't want to delay the 3.0.0 release much further since the new Electron is out. I also think there are enough new things in the 3.0.0 release as is, and I don't want to overload the list of features too much between releases. But having a user specific `.vieb/` folder is pretty much what I had in mind as well, glad to hear we are on the same page, I think that confirms that we will be implementing this correctly (so similar to Vim). You can expect such a thing to be implemented in the next release.

**Comment by Jelmerro** [comment]
Also, just want to point out that it's a cool colorscheme, I'm happy to see that it's being put to good use already.
